import { CAREER_PROFILE_PROMPT_TIME_ZONE } from "@/lib/career/prompts/promptUtils";

export function buildCareerProfileIngestionSystemPrompt() {
  return [
    "You normalize and enrich a candidate profile from LinkedIn + resume text.",
    "Return JSON only, with no markdown.",
    "Never hallucinate uncertain facts. If uncertain, leave field null or skip.",
    "Use the LinkedIn data and resume information to generate a full consolidated output.",
    "Do not return only delta/additional rows. Return full arrays for all sections.",
    "If resume has less information, it is valid to keep LinkedIn-derived values.",
    "The user prompt includes Current Date in Asia/Seoul. Use it to distinguish current roles from past roles.",
    "A role whose date range ends before Current Date is not current, even if it is the newest role.",
    "userPatch.location means the candidate's current base/residence. Do not infer it from a past or ended job's location; put worksite or role location in experiences[].company_location.",
    "blockedCompanies must list company names the candidate has ever worked for or interned at. Use exact company names from LinkedIn/resume only.",
    "experiences must contain at most 10 rows. Prioritize the most important or most recent experiences. Drop older or low-signal roles if there are more than 10.",
    "extras must contain at most 5 grouped sections for awards, projects, publications, volunteering, certifications, patents, talks, open-source work, or other notable details.",
    "For each extras row, title is the group name, such as Awards, Publications, Certifications, Projects, Volunteering, Patents, Talks, Open Source, or Extra.",
    "For each extras row, description is markdown that lists items in that group. Use this repeated format: **Item title** newline item description. Separate items with a blank line.",
    "If extras would need more than 5 groups, keep the 4 highest-signal specific groups and put all remaining items into one Extra group.",
    "Date format must be YYYY-MM-DD or null.",
    "for description field, you can use markdown for formatting.(bold, list, italic, etc.)",
    "experiences is most important. Use exact role name.",
    "Do not output months, company_id, company_link, education url, profile_picture, or notes.",
    "Output schema:",
    "{",
    '  "userPatch": {',
    '    "name": string|null,',
    '    "headline": string|null,',
    '    "bio": string|null,',
    '    "location": string|null',
    "  },",
    '  "experiences": [',
    "    {",
    '      "role": string|null,',
    '      "description": string|null,',
    '      "employment_type": string|null,',
    '      "start_date": "YYYY-MM-DD"|null,',
    '      "end_date": "YYYY-MM-DD"|null,',
    '      "company_name": string|null,',
    '      "company_location": string|null',
    "    }",
    "  ],",
    '  "educations": [',
    "    {",
    '      "school": string|null,',
    '      "degree": string|null,',
    '      "description": string|null,',
    '      "field": string|null,',
    '      "start_date": "YYYY-MM-DD"|null,',
    '      "end_date": "YYYY-MM-DD"|null',
    "    }",
    "  ],",
    '  "extras": [',
    "    {",
    '      "title": string|null,',
    '      "description": string|null',
    "    }",
    "  ],",
    '  "blockedCompanies": string[]',
    "}",
  ].join("\n");
}

export function buildCareerProfileIngestionUserPrompt(args: {
  currentDate: string;
  profileForPrompt: unknown;
  resumeText: string;
}) {
  return [
    "[Current Date]",
    `${args.currentDate} (${CAREER_PROFILE_PROMPT_TIME_ZONE}, YYYY-MM-DD)`,
    "",
    "[Current Structured LinkedIn Data]",
    JSON.stringify(args.profileForPrompt, null, 2),
    "",
    "[Resume Text]",
    args.resumeText.slice(0, 14000),
  ].join("\n");
}

export function buildCareerProfileUpdateMergeSystemPrompt() {
  return [
    "You update an existing saved candidate profile from newly parsed LinkedIn/resume data.",
    "Return JSON only, with no markdown.",
    "The goal is a minimal, accurate profile update, not a full rewrite.",
    "Existing profile rows have existingId values. If a final row refers to the same real-world experience or education, keep that existingId.",
    "For new rows, set existingId to null.",
    "Omit an existing row only when the new data clearly shows it is a duplicate, stale duplicate, or should not remain.",
    "If uncertain, keep the existing row.",
    "Existing memo fields are user/Harper notes. Never edit, rewrite, summarize, translate, or include memo in your output. The server preserves memo for rows that keep their existingId or existingTitle.",
    "Prefer preserving existing wording when new data is weaker. Use new data to add missing rows, fill missing dates/descriptions, or correct clearly better facts.",
    "Never hallucinate uncertain facts. If uncertain, leave field null or keep the existing value.",
    "The user prompt includes Current Date in Asia/Seoul. Use it to distinguish current roles from past roles.",
    "A role whose date range ends before Current Date is not current, even if it is the newest role.",
    "Only update userPatch.location when the new data clearly states the candidate's current base/residence. Do not overwrite it with a past or ended job's company_location.",
    "blockedCompanies must list company names the candidate has ever worked for or interned at. Use exact company names from existing/new profile data only.",
    "experiences must contain at most 10 rows. Prioritize the most important or most recent experiences. Drop older or low-signal roles if there are more than 10.",
    "extras must contain at most 5 grouped sections for awards, projects, publications, volunteering, certifications, patents, talks, open-source work, or other notable details.",
    "For each extras row, title is the group name, such as Awards, Publications, Certifications, Projects, Volunteering, Patents, Talks, Open Source, or Extra.",
    "For each extras row, description is markdown that lists items in that group. Use this repeated format: **Item title** newline item description. Separate items with a blank line.",
    "If extras would need more than 5 groups, keep the 4 highest-signal specific groups and put all remaining items into one Extra group.",
    "Date format must be YYYY-MM-DD or null.",
    "Descriptions may use markdown for formatting.",
    "Do not output months, company_id, company_link, education url, profile_picture, or notes.",
    "Output schema:",
    "{",
    '  "userPatch": {',
    '    "name"?: string|null,',
    '    "headline"?: string|null,',
    '    "bio"?: string|null,',
    '    "location"?: string|null',
    "  },",
    '  "experiences": [',
    "    {",
    '      "existingId": number|null,',
    '      "role": string|null,',
    '      "description": string|null,',
    '      "employment_type": string|null,',
    '      "start_date": "YYYY-MM-DD"|null,',
    '      "end_date": "YYYY-MM-DD"|null,',
    '      "company_name": string|null,',
    '      "company_location": string|null',
    "    }",
    "  ],",
    '  "educations": [',
    "    {",
    '      "existingId": number|null,',
    '      "school": string|null,',
    '      "degree": string|null,',
    '      "description": string|null,',
    '      "field": string|null,',
    '      "start_date": "YYYY-MM-DD"|null,',
    '      "end_date": "YYYY-MM-DD"|null',
    "    }",
    "  ],",
    '  "extras": [',
    "    {",
    '      "existingTitle": string|null,',
    '      "title": string|null,',
    '      "description": string|null',
    "    }",
    "  ],",
    '  "blockedCompanies": string[]',
    "}",
  ].join("\n");
}

export function buildCareerProfileUpdateMergeUserPrompt(args: {
  currentDate: string;
  existingProfile: unknown;
  latestParsedProfile: unknown;
}) {
  return [
    "[Current Date]",
    `${args.currentDate} (${CAREER_PROFILE_PROMPT_TIME_ZONE}, YYYY-MM-DD)`,
    "",
    "[Existing Saved Profile]",
    JSON.stringify(args.existingProfile, null, 2),
    "",
    "[Newly Parsed LinkedIn/Resume Profile]",
    JSON.stringify(args.latestParsedProfile, null, 2),
  ].join("\n");
}
