/** Shared structural contract for company-visible reports, not a fit judge. */
function text(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
function record(value: unknown): Record<string, any> {
  return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, any> : {};
}

export function parseCompanyCandidatePresentation(value: unknown, criteria: Array<{name: string; criteria?: string}>) {
  const raw = record(value);
  const introduction = text(raw.introduction);
  const names = new Set(criteria.map(item => item.name));
  if (!introduction || introduction.length > 1200 || !Array.isArray(raw.criteriaEvaluations)) {
    throw new Error("companyPresentation requires a compact introduction and criteriaEvaluations array");
  }
  const seen = new Set<string>();
  const criteriaEvaluations = raw.criteriaEvaluations.map((value: unknown) => {
    const item = record(value);
    const name = text(item.name), content = text(item.content);
    const fitness = text(item.fitness);
    if (!names.has(name) || seen.has(name) || !content || content.length > 1800 ||
        !["excellent", "good", "uncertain", "bad"].includes(fitness)) {
      throw new Error("Invalid or duplicate company criterion; use the current supplied criteria exactly once");
    }
    seen.add(name);
    return { name, content, fitness: fitness as "excellent" | "good" | "uncertain" | "bad",
      criterionDefinition: criteria.find(item => item.name === name)?.criteria ?? "" };
  });
  if (seen.size !== names.size) throw new Error("Every current company criterion requires an evaluation");
  return { introduction, criteriaEvaluations };
}

/** Never label an assessment of old criteria as an assessment of the current ones.
 * Definitions are stamped from the input by code, never generated by the model. */
export function currentCompanyCriteriaEvaluations(value: unknown, criteria: Array<{name: string; criteria?: string}>) {
  if (!Array.isArray(value) || value.length !== criteria.length) return [];
  const definitions = new Map(criteria.map(item => [item.name, item.criteria ?? ""]));
  const seen = new Set<string>();
  for (const entry of value) {
    const item = record(entry);
    if (!definitions.has(item.name) || seen.has(item.name) ||
        item.criterionDefinition !== definitions.get(item.name)) return [];
    seen.add(item.name);
  }
  return value;
}
