import { careerT } from "@/lib/career/translatedCareerMessage";
export const TALENT_MESSAGE_TYPE_OPPORTUNITY_FEEDBACK_NOTE =
  "opportunity_feedback_note";

const OPPORTUNITY_FEEDBACK_SYSTEM_ACTION_LOG_PREFIX = [
  "[System action log]",
  "This opportunity feedback note was generated by Harper after the user clicked a save/dislike control. It is not a user-authored chat message.",
].join(" ");

export function buildOpportunityFeedbackNoteContent(args: {
  action: "positive" | "negative";
  companyName: string;
  sourceType: "external" | "internal" | string | null | undefined;
  title: string;
}) {
  const title = args.title.replace(/\s+/g, " ").trim() || "Unknown role";
  const companyName =
    args.companyName.replace(/\s+/g, " ").trim() || "Unknown company";
  const sourceLabel = args.sourceType === "internal" ? "Internal" : "External";
  const actionLabel =
    args.action === "positive"
      ? args.sourceType === "internal"
        ? careerT(
            "ko",
            "career.common.opportunity_feedback_note.0aslysy",
            "수락함"
          )
        : careerT("ko", "career.common.career_history_panel.06mgpci", "저장함")
      : careerT(
          "ko",
          "career.common.career_history_panel.0paqqgp",
          "선호하지 않음"
        );

  return `(${sourceLabel}) ${title} at ${companyName} ${actionLabel}`;
}

export function isOpportunityFeedbackNoteMessageType(
  messageType: string | null | undefined
) {
  return messageType === TALENT_MESSAGE_TYPE_OPPORTUNITY_FEEDBACK_NOTE;
}

export function formatTalentMessageContentForLlmPrompt(message: {
  content: string | null | undefined;
  messageType?: string | null;
  message_type?: string | null;
}) {
  const content = String(message.content ?? "");
  if (
    !isOpportunityFeedbackNoteMessageType(
      message.message_type ?? message.messageType
    )
  ) {
    return content;
  }

  const normalizedContent = content.replace(/\s+/g, " ").trim();
  return normalizedContent
    ? `${OPPORTUNITY_FEEDBACK_SYSTEM_ACTION_LOG_PREFIX}\nAction note: ${normalizedContent}`
    : OPPORTUNITY_FEEDBACK_SYSTEM_ACTION_LOG_PREFIX;
}
