// Local-only schema replica and PostgREST transport for the contact scenario QA.
import { readFileSync, existsSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { createServer } from "node:http";
import { spawn } from "node:child_process";
import path from "node:path";

const dir = process.env.CONTACT_QA_SANDBOX;
if (!dir?.startsWith("/tmp/harper-contact-live."))
  throw Error("Explicit isolated temp directory required");
const require = createRequire(path.join(dir, "package.json"));
const { default: EmbeddedPostgres } = await import(
  require.resolve("embedded-postgres")
);
const artifact = JSON.parse(
  readFileSync(
    new URL(
      "../docs/evaluation/company-talent-contacts/private/schema-and-identities-v2.json",
      import.meta.url
    )
  )
);
const pg = new EmbeddedPostgres({
  databaseDir: path.join(dir, "pgdata"),
  user: "postgres",
  password: "isolated-contact-qa",
  port: 55437,
  persistent: true,
  onLog: () => {},
  onError: (m) => console.error(String(m)),
});
if (!existsSync(path.join(dir, "pgdata/PG_VERSION"))) await pg.initialise();
await pg.start();
const db = pg.getPgClient();
await db.connect();
const q = (s) => '"' + s.replaceAll('"', '""') + '"';
const errors = [];
async function attempt(kind, name, sql) {
  try {
    await db.query(sql);
  } catch (e) {
    errors.push({ kind, name, error: e.message });
  }
}
if (
  !(await db.query("select to_regclass('public.company_workspace') as t"))
    .rows[0].t
) {
  await db.query(`create role anon; create role authenticated; create role service_role bypassrls; create role supabase_admin;
    create schema auth; create schema extensions; create extension pgcrypto with schema extensions;
    create domain public.vector as real[];
    create table auth.users(id uuid primary key,email text);
    create function auth.uid() returns uuid language sql stable as $$ select null::uuid $$;
    create function auth.role() returns text language sql stable as $$ select 'service_role'::text $$;
    create function auth.jwt() returns jsonb language sql stable as $$ select '{}'::jsonb $$;
    set check_function_bodies=false; set search_path=public,extensions;`);
  for (const e of artifact.enums)
    await db.query(
      `create type public.${q(e.name)} as enum (${e.labels.map((x) => "'" + x.replaceAll("'", "''") + "'").join(",")})`
    );
  for (const s of artifact.sequences)
    await db.query(`create sequence public.${q(s.sequence_name)}`);
  const tables = Map.groupBy
    ? Map.groupBy(artifact.columns, (c) => c.table_name)
    : artifact.columns.reduce(
        (m, c) => (
          m.has(c.table_name) || m.set(c.table_name, []),
          m.get(c.table_name).push(c),
          m
        ),
        new Map()
      );
  for (const [table, cols] of tables) {
    const defs = cols.map(
      (c) =>
        `${q(c.name)} ${c.type.replace(/vector\(\d+\)/g, "vector")} ${c.identity ? "generated by default as identity" : c.generated ? `generated always as (${c.default_expr}) stored` : c.default_expr ? `default ${c.default_expr}` : ""} ${c.not_null ? "not null" : ""}`
    );
    await attempt(
      "table",
      table,
      `create table public.${q(table)} (${defs.join(",")})`
    );
  }
  for (const c of artifact.constraints)
    await attempt(
      "constraint",
      c.name,
      `alter table ${c.table_name} add constraint ${q(c.name)} ${c.definition}`
    );
  for (const f of artifact.functions)
    await attempt("function", f.name, f.definition);
  for (const i of artifact.indexes)
    await attempt("index", i.name, i.definition);
  // Restore exact product triggers, excluding network/embedding automation that
  // belongs to unavailable production services, not this contact/pipeline test.
  const excluded = [];
  for (const t of artifact.triggers) {
    const f = artifact.functions.find((f) => f.name === t.function_name);
    if (
      /net\.http|http_post|supabase_functions|embedding|refresh.*company.*context/i.test(
        f?.definition ?? ""
      )
    ) {
      excluded.push(t.name);
      continue;
    }
    await attempt("trigger", t.name, t.definition);
  }
  for (const file of [
    "20260922082129_company_agent_web_action_turns.sql",
    "20260923063625_unified_company_talent_contacts.sql",
  ]) {
    await db.query(
      readFileSync(
        new URL(`../supabase/migrations/${file}`, import.meta.url),
        "utf8"
      )
    );
  }
  await db.query(
    "grant usage on schema public to service_role; grant all on all tables in schema public to service_role; grant all on all sequences in schema public to service_role;"
  );
  writeFileSync(
    path.join(dir, "restore-report.json"),
    JSON.stringify(
      {
        errors,
        excluded,
        embeddingType: "unused vector columns restored as real[] domain",
      },
      null,
      2
    ),
    { mode: 0o600 }
  );
  console.log(
    JSON.stringify({
      restoredTables: tables.size,
      restoreErrors: errors.length,
      excludedTriggers: excluded,
    })
  );
}
await db.end();
const nativeLib = path.join(
  dir,
  "node_modules/@embedded-postgres/darwin-arm64/native/lib"
);
const rest = spawn(path.join(dir, "postgrest"), [], {
  env: {
    ...process.env,
    DYLD_LIBRARY_PATH: nativeLib,
    PGRST_DB_URI:
      "postgresql://postgres:isolated-contact-qa@127.0.0.1:55437/postgres",
    PGRST_DB_ANON_ROLE: "postgres",
    PGRST_DB_SCHEMAS: "public",
    PGRST_SERVER_HOST: "127.0.0.1",
    PGRST_SERVER_PORT: "55438",
  },
  stdio: ["ignore", "ignore", "pipe"],
});
rest.stderr.on("data", (x) => {
  if (/error/i.test(String(x))) console.error(String(x));
});
const gateway = createServer(async (req, res) => {
  const headers = {
    "access-control-allow-origin": "*",
    "access-control-allow-headers": "*",
    "access-control-allow-methods": "GET,POST,PATCH,DELETE,OPTIONS",
  };
  if (req.method === "OPTIONS") {
    res.writeHead(200, headers);
    res.end();
    return;
  }
  try {
    const url = new URL(req.url, "http://127.0.0.1");
    if (url.pathname.startsWith("/auth/v1/")) {
      const token = String(req.headers.authorization ?? "").replace(
        /^Bearer /,
        ""
      );
      const id = url.pathname.startsWith("/auth/v1/admin/users/")
        ? url.pathname.split("/").pop()
        : token.replace(/^qa:/, "");
      const t = artifact.talents.find((t) => t.user_id === id);
      if (!t) {
        res.writeHead(401, headers);
        res.end("{}");
        return;
      }
      const user = {
        id: t.user_id,
        email: t.email,
        aud: "authenticated",
        role: "authenticated",
        app_metadata: { provider: "email" },
        user_metadata: { name: t.name, full_name: t.name },
        created_at: t.created_at,
      };
      res.writeHead(200, { ...headers, "content-type": "application/json" });
      res.end(JSON.stringify(user));
      return;
    }
    if (!url.pathname.startsWith("/rest/v1/"))
      throw Error("Only isolated REST/auth endpoints are available");
    const chunks = [];
    for await (const chunk of req) chunks.push(chunk);
    const upstreamHeaders = { ...req.headers };
    delete upstreamHeaders.authorization;
    delete upstreamHeaders.host;
    delete upstreamHeaders["content-length"];
    const response = await fetch(
      "http://127.0.0.1:55438" +
        url.pathname.replace("/rest/v1", "") +
        url.search,
      {
        method: req.method,
        headers: upstreamHeaders,
        body: ["GET", "HEAD"].includes(req.method)
          ? undefined
          : Buffer.concat(chunks),
      }
    );
    res.writeHead(response.status, {
      ...Object.fromEntries(response.headers),
      ...headers,
    });
    res.end(Buffer.from(await response.arrayBuffer()));
  } catch (error) {
    res.writeHead(500, { ...headers, "content-type": "application/json" });
    res.end(JSON.stringify({ error: error.message }));
  }
});
gateway.listen(55439, "127.0.0.1", () =>
  console.log("CONTACT_QA_SANDBOX_READY http://127.0.0.1:55439")
);
async function stop() {
  gateway.close();
  rest.kill("SIGTERM");
  await pg.stop();
  process.exit(0);
}
process.on("SIGTERM", stop);
process.on("SIGINT", stop);
