import { execFileSync } from "node:child_process";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import postgres, { type Sql } from "postgres";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MIGRATIONS = [
  "20260805010000_company_role_request_compat.sql",
  "20260805020000_company_agent_memory_events_and_proposals.sql",
  "20260805030000_company_data_changes_rpc.sql",
  "20260805040000_company_role_request_legacy_write_guard.sql",
  "20260805060000_finalize_slack_company_agent_reply.sql",
  "20260805070000_reassociate_company_workspace_db.sql",
] as const;

const IDS = {
  workspaceA: "00000000-0000-4000-8000-000000000001",
  workspaceB: "00000000-0000-4000-8000-000000000002",
  user: "00000000-0000-4000-8000-000000000010",
  conflictRole: "00000000-0000-4000-8000-000000000101",
  legacyRole: "00000000-0000-4000-8000-000000000102",
  missingExtensionRole: "00000000-0000-4000-8000-000000000103",
  internalOnlyRole: "00000000-0000-4000-8000-000000000104",
  externalRole: "00000000-0000-4000-8000-000000000105",
  otherWorkspaceRole: "00000000-0000-4000-8000-000000000106",
  oversizedRole: "00000000-0000-4000-8000-000000000107",
  conversation: "00000000-0000-4000-8000-000000000201",
  slackChannel: "00000000-0000-4000-8000-000000000301",
  slackThread: "00000000-0000-4000-8000-000000000302",
  normalReplyJob: "00000000-0000-4000-8000-000000000401",
  adoptedReplyJob: "00000000-0000-4000-8000-000000000402",
  conflictingReplyJob: "00000000-0000-4000-8000-000000000403",
} as const;

const BASELINE_SQL = String.raw`
create extension if not exists pgcrypto;

create table public.company_db (
  id bigint generated by default as identity primary key,
  name text,
  description text,
  logo text,
  website_url text,
  linkedin_url text,
  short_description text,
  funding_url text,
  location text,
  founded_year integer,
  employee_count_range jsonb,
  specialities text not null default '',
  investors text,
  related_links text[],
  last_updated_at timestamptz not null default now()
);

create table public.company_workspace (
  company_workspace_id uuid primary key default gen_random_uuid(),
  company_db_id bigint references public.company_db(id) on delete set null,
  company_name text not null,
  published_name text,
  company_description text,
  pitch text,
  request text,
  logo_url text,
  homepage_url text,
  career_url text,
  linkedin_url text,
  brief text,
  is_internal boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.company_roles (
  role_id uuid primary key default gen_random_uuid(),
  company_workspace_id uuid not null
    references public.company_workspace(company_workspace_id) on delete cascade,
  name text not null,
  description text,
  description_summary text,
  external_jd_url text,
  location_text text,
  status text not null default 'active',
  work_mode text,
  type text[] not null default '{}',
  request text,
  source_type text not null default 'internal',
  source_provider text,
  source_job_id text,
  posted_at timestamptz,
  expires_at timestamptz,
  is_expired boolean not null default false,
  opportunity_search_tsv tsvector,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.test_refresh_company_role_search()
returns trigger language plpgsql as $$
begin
  new.opportunity_search_tsv := to_tsvector(
    'simple', concat_ws(' ', new.name, new.description, new.request)
  );
  return new;
end;
$$;
create trigger company_roles_test_search
before insert or update of name, description, request on public.company_roles
for each row execute function public.test_refresh_company_role_search();

create table public.company_internal_roles (
  role_id uuid primary key
    references public.company_roles(role_id) on delete cascade,
  request text,
  considerations jsonb not null default '{}'::jsonb,
  questions jsonb,
  is_auto boolean not null default false,
  is_require_linkedin boolean,
  is_require_resume boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.company_data (
  company_workspace_id uuid primary key
    references public.company_workspace(company_workspace_id) on delete cascade,
  total_funding_raised text,
  main_investors text,
  last_funding_stage text,
  last_funding_round_description text,
  searched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.company_users (
  user_id uuid primary key,
  name text,
  email text
);

create table public.company_conversations (
  id uuid primary key default gen_random_uuid(),
  company_workspace_id uuid not null
    references public.company_workspace(company_workspace_id) on delete cascade,
  role_id uuid references public.company_roles(role_id) on delete set null,
  title text,
  last_message_at timestamptz,
  last_message_id bigint,
  summary_cursor_message_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.company_messages (
  id bigserial primary key,
  conversation_id uuid not null
    references public.company_conversations(id) on delete cascade,
  company_workspace_id uuid not null
    references public.company_workspace(company_workspace_id) on delete cascade,
  role_id uuid references public.company_roles(role_id) on delete set null,
  company_user_id uuid references public.company_users(user_id) on delete set null,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  message_type text not null default 'chat',
  model text,
  status text not null default 'completed',
  mentions jsonb not null default '[]'::jsonb,
  thinking_logs jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  slack_thread_id uuid,
  slack_message_ts text,
  slack_user_id text,
  created_at timestamptz not null default now()
);

create table public.company_slack_integrations (
  company_workspace_id uuid primary key
    references public.company_workspace(company_workspace_id) on delete cascade,
  slack_team_id text not null
);

create table public.company_slack_channels (
  id uuid primary key default gen_random_uuid(),
  company_workspace_id uuid not null
    references public.company_slack_integrations(company_workspace_id) on delete cascade,
  slack_team_id text not null,
  slack_channel_id text not null,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.company_slack_threads (
  id uuid primary key default gen_random_uuid(),
  channel_id uuid not null
    references public.company_slack_channels(id) on delete cascade,
  role_id uuid references public.company_roles(role_id) on delete set null,
  slack_thread_ts text not null,
  created_by_harper boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.company_messages
  add constraint company_messages_slack_thread_id_fkey
  foreign key (slack_thread_id)
  references public.company_slack_threads(id)
  on delete set null;

create unique index company_messages_slack_message_uidx
  on public.company_messages(slack_thread_id, slack_message_ts)
  where message_type = 'slack'
    and slack_thread_id is not null
    and nullif(slack_message_ts, '') is not null;

create table public.slack_reply_jobs (
  id uuid primary key default gen_random_uuid(),
  slack_event_id text not null unique,
  thread_id uuid not null
    references public.company_slack_threads(id) on delete cascade,
  user_message_id bigint unique
    references public.company_messages(id) on delete set null,
  response_message_id bigint
    references public.company_messages(id) on delete set null,
  trigger_kind text not null,
  slack_message_ts text not null,
  slack_user_id text,
  prompt text not null,
  status text not null default 'queued',
  attempt_count integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  response_text text,
  slack_response_ts text,
  last_error text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);
`;

type Db = Sql<Record<string, unknown>>;

function fail(message: string): never {
  throw new Error(`[org-agent-db] ${message}`);
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) fail(message);
}

function value<T>(rows: readonly Record<string, unknown>[], key: string): T {
  assert(rows.length === 1, `expected one row while reading ${key}`);
  return rows[0]![key] as T;
}

async function expectDbError(
  label: string,
  operation: () => Promise<unknown>,
  pattern: RegExp
) {
  try {
    await operation();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    assert(
      pattern.test(message),
      `${label} failed with an unexpected error: ${message}`
    );
    return;
  }
  fail(`${label} unexpectedly succeeded`);
}

function logPass(label: string) {
  process.stdout.write(`ok - ${label}\n`);
}

function isLoopback(hostname: string) {
  const normalized = hostname.replace(/^\[|\]$/g, "").toLowerCase();
  return (
    normalized === "localhost" ||
    normalized === "127.0.0.1" ||
    normalized === "::1"
  );
}

function parseStatusEnv(output: string) {
  for (const line of output.split(/\r?\n/)) {
    const match = line.match(/^DB_URL=(?:"([^"]+)"|'([^']+)'|(\S+))$/);
    if (match) return match[1] || match[2] || match[3] || null;
  }
  return null;
}

function discoverDatabaseUrl() {
  if (process.env.ORG_AGENT_TEST_DATABASE_URL) {
    return process.env.ORG_AGENT_TEST_DATABASE_URL;
  }
  try {
    const output = execFileSync(
      path.join(ROOT, "node_modules", ".bin", "supabase"),
      ["status", "--output", "env", "--workdir", ROOT],
      {
        cwd: ROOT,
        encoding: "utf8",
        env: { ...process.env, SUPABASE_TELEMETRY_DISABLED: "1" },
        stdio: ["ignore", "pipe", "pipe"],
      }
    );
    const discovered = parseStatusEnv(output);
    if (discovered) return discovered;
  } catch {
    // The actionable prerequisite error below is deliberately stable for CI.
  }
  fail(
    "No local Postgres is available. Start a Docker-compatible runtime, run " +
      "`pnpm exec supabase start`, or set ORG_AGENT_TEST_DATABASE_URL to a loopback Postgres URL."
  );
}

function guardDatabaseUrl(raw: string) {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    fail("ORG_AGENT_TEST_DATABASE_URL is not a valid PostgreSQL URL");
  }
  assert(
    url.protocol === "postgres:" || url.protocol === "postgresql:",
    "ORG_AGENT_TEST_DATABASE_URL must use postgres:// or postgresql://"
  );
  assert(
    isLoopback(url.hostname),
    "refusing to run DB tests against a non-loopback host"
  );

  const protectedNames = [
    "DATABASE_URL",
    "POSTGRES_URL",
    "POSTGRES_URL_NON_POOLING",
    "POSTGRES_PRISMA_URL",
    "SUPABASE_DB_URL",
    "PRODUCTION_DATABASE_URL",
    "STAGING_DATABASE_URL",
  ];
  for (const name of protectedNames) {
    if (process.env[name] && process.env[name] === raw) {
      fail(
        `refusing to use ORG_AGENT_TEST_DATABASE_URL because it equals ${name}`
      );
    }
  }
  return url;
}

function maintenanceUrl(url: URL) {
  const result = new URL(url);
  result.pathname = "/postgres";
  result.searchParams.delete("pgbouncer");
  return result.toString();
}

function databaseUrl(url: URL, database: string) {
  const result = new URL(url);
  result.pathname = `/${database}`;
  result.searchParams.delete("pgbouncer");
  return result.toString();
}

async function ensureLocalRoles(sql: Db) {
  await sql.unsafe(`
    do $$
    begin
      if not exists (select 1 from pg_roles where rolname = 'anon') then
        create role anon nologin;
      end if;
      if not exists (select 1 from pg_roles where rolname = 'authenticated') then
        create role authenticated nologin;
      end if;
      if not exists (select 1 from pg_roles where rolname = 'service_role') then
        create role service_role nologin bypassrls;
      end if;
      if not exists (select 1 from pg_roles where rolname = 'harper_worker') then
        create role harper_worker nologin;
      end if;
    end;
    $$;
  `);
}

async function applyMigration(sql: Db, filename: (typeof MIGRATIONS)[number]) {
  const body = await readFile(
    path.join(ROOT, "supabase", "migrations", filename),
    "utf8"
  );
  await sql.unsafe(body);
}

function firstRow(result: unknown): Record<string, unknown> {
  const rows = result as Record<string, unknown>[];
  assert(
    Array.isArray(rows) && rows.length === 1,
    "expected exactly one database row"
  );
  return rows[0]!;
}

function rpcResult(result: unknown) {
  return firstRow(result).result as Record<string, unknown>;
}

async function installBaseline(sql: Db) {
  await sql.unsafe(BASELINE_SQL);
  const [companyDb] = await sql`
    insert into public.company_db(name, specialities)
    values ('Acme database mirror', '')
    returning id
  `;
  assert(companyDb, "company_db fixture was not created");
  const companyDbId = companyDb.id as number;

  await sql`
    insert into public.company_workspace(
      company_workspace_id, company_db_id, company_name, company_description
    ) values
      (${IDS.workspaceA}::uuid, ${companyDbId}, 'Acme', 'Initial description'),
      (${IDS.workspaceB}::uuid, null, 'Other Co', null)
  `;
  await sql`
    insert into public.company_users(user_id, name, email)
    values (${IDS.user}::uuid, 'DB Tester', 'db-test@example.com')
  `;
  await sql`
    insert into public.company_roles(
      role_id, company_workspace_id, name, request, source_type, is_expired
    ) values
      (${IDS.conflictRole}::uuid, ${IDS.workspaceA}::uuid, 'Conflict Role', 'legacy conflict', 'internal', false),
      (${IDS.legacyRole}::uuid, ${IDS.workspaceA}::uuid, 'Legacy Role', 'legacy request', 'internal', false),
      (${IDS.missingExtensionRole}::uuid, ${IDS.workspaceA}::uuid, 'Missing Extension', 'create extension', 'internal', false),
      (${IDS.internalOnlyRole}::uuid, ${IDS.workspaceA}::uuid, 'Internal Only', null, 'internal', false),
      (${IDS.externalRole}::uuid, ${IDS.workspaceA}::uuid, 'External Role', null, 'external', false),
      (${IDS.otherWorkspaceRole}::uuid, ${IDS.workspaceB}::uuid, 'Other Workspace Role', 'other request', 'internal', false),
      (${IDS.oversizedRole}::uuid, ${IDS.workspaceA}::uuid, 'Oversized Legacy Role', ${"L".repeat(
        20_001
      )}, 'internal', false)
  `;
  await sql`
    insert into public.company_internal_roles(role_id, request) values
      (${IDS.conflictRole}::uuid, 'internal conflict'),
      (${IDS.legacyRole}::uuid, null),
      (${IDS.internalOnlyRole}::uuid, 'internal-only request'),
      (${IDS.externalRole}::uuid, 'external request'),
      (${IDS.otherWorkspaceRole}::uuid, 'other request')
  `;
}

async function testRequestMigration(sql: Db, notices: string[]) {
  notices.length = 0;
  await expectDbError(
    "request conflict migration",
    () => applyMigration(sql, MIGRATIONS[0]),
    /conflicting legacy\/internal values/i
  );
  assert(
    notices.some(
      (notice) =>
        notice.includes("legacy_only=3") &&
        notice.includes("internal_only=2") &&
        notice.includes("conflicts=1")
    ),
    "migration preflight did not report all request reconciliation sets"
  );
  assert(
    notices.some(
      (notice) =>
        notice.includes("excluded_external_requests=1") &&
        notice.includes("external_extensions_to_remove=1") &&
        notice.includes("target_over_20000=1") &&
        notice.includes("target_max_length=20001")
    ),
    "migration preflight did not report external and length risk counts"
  );
  const rollbackCheck = firstRow(
    await sql`
    select
      role.request as legacy,
      internal_role.request as internal,
      to_regprocedure('public.sync_legacy_company_role_request_to_internal_v1()') as bridge
    from public.company_roles role
    join public.company_internal_roles internal_role on internal_role.role_id = role.role_id
    where role.role_id = ${IDS.conflictRole}::uuid
  `
  );
  assert(
    rollbackCheck.legacy === "legacy conflict",
    "failed migration changed the legacy request"
  );
  assert(
    rollbackCheck.internal === "internal conflict",
    "failed migration changed the internal request"
  );
  assert(
    rollbackCheck.bridge === null,
    "failed migration leaked the compatibility trigger function"
  );
  logPass("request conflict abort is transactional");

  await sql`
    update public.company_internal_roles
    set request = 'legacy conflict'
    where role_id = ${IDS.conflictRole}::uuid
  `;
  notices.length = 0;
  await applyMigration(sql, MIGRATIONS[0]);
  assert(
    notices.some(
      (notice) =>
        notice.includes("legacy_only=3") &&
        notice.includes("internal_only=2") &&
        notice.includes("conflicts=0")
    ),
    "successful migration preflight did not report reconciled request counts"
  );

  const rows = await sql`
    select
      role.role_id,
      role.request as legacy,
      internal_role.request as internal
    from public.company_roles role
    left join public.company_internal_roles internal_role on internal_role.role_id = role.role_id
    order by role.role_id
  `;
  const byRole = new Map(rows.map((row) => [String(row.role_id), row]));
  assert(
    byRole.get(IDS.legacyRole)?.internal === "legacy request",
    "legacy request was not backfilled"
  );
  assert(
    byRole.get(IDS.missingExtensionRole)?.internal === "create extension",
    "missing internal extension was not created"
  );
  assert(
    byRole.get(IDS.internalOnlyRole)?.legacy === "internal-only request",
    "internal-only request was not mirrored to legacy"
  );
  assert(
    byRole.get(IDS.externalRole)?.legacy === "external request" &&
      byRole.get(IDS.externalRole)?.internal === null,
    "external-only extension request was not preserved on the parent before cleanup"
  );
  assert(
    String(byRole.get(IDS.oversizedRole)?.legacy).length === 20_001 &&
      byRole.get(IDS.oversizedRole)?.internal ===
        byRole.get(IDS.oversizedRole)?.legacy,
    "oversized legacy request was not preserved and mirrored byte-for-byte"
  );
  logPass(
    "request backfill preserves legacy readers and excludes external roles"
  );

  await sql`
    update public.company_roles
    set request = 'old writer update'
    where role_id = ${IDS.legacyRole}::uuid
  `;
  const bridged = firstRow(
    await sql`
    select request from public.company_internal_roles
    where role_id = ${IDS.legacyRole}::uuid
  `
  );
  assert(
    bridged.request === "old writer update",
    "rolling legacy writer bridge did not sync"
  );

  await sql`
    update public.company_roles
    set source_type = 'external'
    where role_id = ${IDS.legacyRole}::uuid
  `;
  const externalized = firstRow(
    await sql`
    select role.request,
           exists (
             select 1 from public.company_internal_roles internal_role
             where internal_role.role_id = role.role_id
           ) as has_extension
    from public.company_roles role
    where role.role_id = ${IDS.legacyRole}::uuid
  `
  );
  assert(
    externalized.request === "old writer update" &&
      externalized.has_extension === false,
    "rolling bridge did not preserve the parent request and remove the external extension"
  );

  await sql`
    update public.company_roles
    set source_type = 'internal', request = 'old writer returned internal'
    where role_id = ${IDS.legacyRole}::uuid
  `;
  const internalized = firstRow(
    await sql`
    select role.request as legacy_request, internal_role.request as internal_request
    from public.company_roles role
    join public.company_internal_roles internal_role on internal_role.role_id = role.role_id
    where role.role_id = ${IDS.legacyRole}::uuid
  `
  );
  assert(
    internalized.legacy_request === "old writer returned internal" &&
      internalized.internal_request === "old writer returned internal",
    "rolling bridge did not recreate the extension on external to internal transition"
  );
  await expectDbError(
    "external role extension scope",
    () => sql`
      insert into public.company_internal_roles(role_id, request)
      values (${IDS.externalRole}::uuid, 'must not persist')
    `,
    /only available for internal roles/i
  );
  logPass(
    "rolling legacy bridge syncs requests and preserves extension scope across source transitions"
  );
}

async function applyRemainingMigrations(sql: Db) {
  await applyMigration(sql, MIGRATIONS[1]);
  await applyMigration(sql, MIGRATIONS[2]);
  await applyMigration(sql, MIGRATIONS[3]);
  await applyMigration(sql, MIGRATIONS[4]);
  await applyMigration(sql, MIGRATIONS[5]);
}

async function testInternalRoleChildUpdateLockOrder(sql: Db, lockHolder: Db) {
  let holderTransactionOpen = false;
  try {
    await lockHolder.unsafe("begin");
    holderTransactionOpen = true;
    await lockHolder`
      select role_id
      from public.company_roles
      where role_id = ${IDS.legacyRole}::uuid
      for update
    `;
    await sql`select set_config('lock_timeout', '200ms', false)`;
    await sql`
      update public.company_internal_roles
      set is_auto = true
      where role_id = ${IDS.legacyRole}::uuid
    `;
    await lockHolder.unsafe("rollback");
    holderTransactionOpen = false;
    assert(
      value<boolean>(
        await sql`
          select is_auto from public.company_internal_roles
          where role_id = ${IDS.legacyRole}::uuid
        `,
        "is_auto"
      ) === true,
      "ordinary internal role child update did not complete under a parent lock"
    );
    logPass(
      "ordinary internal role updates do not invert the parent-child lock order"
    );
  } finally {
    if (holderTransactionOpen) {
      await lockHolder.unsafe("rollback").catch(() => undefined);
    }
    await sql`select set_config('lock_timeout', '0', false)`;
    await sql`
      update public.company_internal_roles
      set is_auto = false
      where role_id = ${IDS.legacyRole}::uuid
    `;
  }
}

async function testMemoryScopeSerialization(sql: Db, lockHolder: Db) {
  let holderTransactionOpen = false;
  try {
    await lockHolder.unsafe("begin");
    holderTransactionOpen = true;
    await lockHolder`
      update public.company_roles
      set source_type = 'external'
      where role_id = ${IDS.legacyRole}::uuid
    `;
    await sql`select set_config('lock_timeout', '200ms', false)`;
    await expectDbError(
      "memory insert waits for role scope transition",
      () => sql`
        insert into public.company_memories(company_workspace_id, role_id, content)
        values (${IDS.workspaceA}::uuid, ${IDS.legacyRole}::uuid, 'Racy memory')
      `,
      /lock timeout|canceling statement due to lock timeout/i
    );

    await lockHolder.unsafe("commit");
    holderTransactionOpen = false;
    await expectDbError(
      "memory insert sees committed external role",
      () => sql`
        insert into public.company_memories(company_workspace_id, role_id, content)
        values (${IDS.workspaceA}::uuid, ${IDS.legacyRole}::uuid, 'Racy memory')
      `,
      /only available for internal roles/i
    );
    logPass("memory insert serializes with concurrent role externalization");
  } finally {
    if (holderTransactionOpen) {
      await lockHolder.unsafe("rollback").catch(() => undefined);
    }
    await sql`select set_config('lock_timeout', '0', false)`;
    await sql`
      update public.company_roles
      set source_type = 'internal'
      where role_id = ${IDS.legacyRole}::uuid
        and source_type is distinct from 'internal'
    `;
  }
}

async function testMemoryConstraints(sql: Db, lockHolder: Db) {
  await testInternalRoleChildUpdateLockOrder(sql, lockHolder);
  await testMemoryScopeSerialization(sql, lockHolder);
  await sql`
    insert into public.company_memories(company_workspace_id, content)
    values (${IDS.workspaceA}::uuid, 'Workspace memory')
  `;
  await expectDbError(
    "duplicate workspace memory",
    () => sql`
      insert into public.company_memories(company_workspace_id, content)
      values (${IDS.workspaceA}::uuid, 'Duplicate memory')
    `,
    /duplicate key|company_memories_workspace_one/i
  );
  await expectDbError(
    "cross-workspace role memory",
    () => sql`
      insert into public.company_memories(company_workspace_id, role_id, content)
      values (${IDS.workspaceA}::uuid, ${IDS.otherWorkspaceRole}::uuid, 'Wrong workspace')
    `,
    /different workspace/i
  );
  await expectDbError(
    "external role memory",
    () => sql`
      insert into public.company_memories(company_workspace_id, role_id, content)
      values (${IDS.workspaceA}::uuid, ${IDS.externalRole}::uuid, 'External memory')
    `,
    /only available for internal roles/i
  );
  await expectDbError(
    "blank memory",
    () => sql`
      insert into public.company_memories(company_workspace_id, role_id, content)
      values (${IDS.workspaceA}::uuid, ${IDS.legacyRole}::uuid, '   ')
    `,
    /company_memories_content_length/i
  );
  await expectDbError(
    "oversized memory",
    () => sql`
      insert into public.company_memories(company_workspace_id, role_id, content)
      values (${IDS.workspaceA}::uuid, ${IDS.legacyRole}::uuid, ${"x".repeat(12_001)})
    `,
    /company_memories_content_length/i
  );
  await sql`
    delete from public.company_memories
    where company_workspace_id = ${IDS.workspaceA}::uuid
  `;
  logPass(
    "memory uniqueness, scope, internal-role, blank, and length constraints"
  );
}

async function testRlsAndGrants(sql: Db) {
  const flags = await sql`
    select relname, relrowsecurity
    from pg_class
    where oid in (
      'public.company_memories'::regclass,
      'public.company_events'::regclass,
      'public.company_agent_update_proposals'::regclass
    )
    order by relname
  `;
  assert(
    flags.length === 3 && flags.every((row) => row.relrowsecurity === true),
    "new tables do not all have RLS enabled"
  );

  const grants = firstRow(
    await sql`
    select
      has_table_privilege('anon', 'public.company_memories', 'SELECT') as anon_read,
      has_table_privilege('authenticated', 'public.company_events', 'INSERT') as authenticated_write,
      has_table_privilege('service_role', 'public.company_memories', 'SELECT,INSERT,UPDATE,DELETE') as service_memory,
      has_function_privilege(
        'service_role',
        'public.apply_company_data_changes_v1(uuid,jsonb,text,text)',
        'EXECUTE'
      ) as service_apply,
      has_function_privilege(
        'anon',
        'public.apply_company_data_changes_v1(uuid,jsonb,text,text)',
        'EXECUTE'
      ) as anon_apply,
      has_function_privilege(
        'service_role',
        'public.apply_company_data_changes_internal_v1(uuid,jsonb,text,text,boolean)',
        'EXECUTE'
      ) as service_private_apply,
      has_function_privilege(
        'service_role',
        'public.validate_company_data_change_value_v1(text,jsonb,text)',
        'EXECUTE'
      ) as service_private_validator,
      has_function_privilege(
        'service_role',
        'public.finalize_slack_company_agent_reply_v1(uuid,text,text)',
        'EXECUTE'
      ) as service_finalize_slack,
      has_function_privilege(
        'anon',
        'public.finalize_slack_company_agent_reply_v1(uuid,text,text)',
        'EXECUTE'
      ) as anon_finalize_slack,
      has_function_privilege(
        'service_role',
        'public.reassociate_company_workspace_db_v1(uuid,bigint,bigint,jsonb,text)',
        'EXECUTE'
      ) as service_reassociate_company_db,
      has_function_privilege(
        'anon',
        'public.reassociate_company_workspace_db_v1(uuid,bigint,bigint,jsonb,text)',
        'EXECUTE'
      ) as anon_reassociate_company_db
  `
  );
  assert(grants.anon_read === false, "anon can read company memories");
  assert(
    grants.authenticated_write === false,
    "authenticated can write company events"
  );
  assert(
    grants.service_memory === true,
    "service_role lacks memory CRUD grants"
  );
  assert(
    grants.service_apply === true,
    "service_role lacks public apply RPC execute"
  );
  assert(grants.anon_apply === false, "anon can execute the apply RPC");
  assert(
    grants.service_private_apply === false,
    "service_role can execute the private apply helper directly"
  );
  assert(
    grants.service_private_validator === false,
    "service_role can execute the private catalog validator directly"
  );
  assert(
    grants.service_finalize_slack === true,
    "service_role lacks Slack reply finalization execute"
  );
  assert(
    grants.anon_finalize_slack === false,
    "anon can execute Slack reply finalization"
  );
  assert(
    grants.service_reassociate_company_db === true,
    "service_role lacks company_db reassociation execute"
  );
  assert(
    grants.anon_reassociate_company_db === false,
    "anon can execute company_db reassociation"
  );
  logPass("RLS and public/private grants are server-only");
}

async function countEvents(sql: Db) {
  return Number(
    value<number>(
      await sql`select count(*)::integer as count from public.company_events`,
      "count"
    )
  );
}

async function testApplyRpcAndGuard(sql: Db, lockHolder: Db) {
  await sql`select set_config('harper.company_role_request_guard_enabled', 'on', false)`;
  await expectDbError(
    "legacy direct-write guard",
    () => sql`
      update public.company_roles
      set request = 'must fail'
      where role_id = ${IDS.legacyRole}::uuid
    `,
    /direct writes to company_roles\.request are disabled/i
  );
  logPass("legacy direct-write guard can be activated after old writers drain");

  const changes = [
    {
      key: "pitch",
      role_id: null,
      expected: null,
      value: "A concise company pitch",
    },
    { key: "founded_year", role_id: null, expected: null, value: 2021 },
    {
      key: "role_request",
      role_id: IDS.legacyRole,
      expected: "old writer update",
      value:
        "## Hard constraints\n\n- Backend experience\n\n## Preferred criteria\n\n- Startup experience",
    },
  ];
  const applied = rpcResult(
    await sql`
    select public.apply_company_data_changes_v1(
      ${IDS.workspaceA}::uuid,
      ${JSON.stringify(changes)}::jsonb,
      'chat',
      'DB Tester · pitch, founded_year, Legacy Role 기준 수정'
    ) as result
  `
  );
  assert(
    applied.status === "updated" && applied.changed_count === 3,
    "apply RPC did not update the full batch"
  );
  const state = firstRow(
    await sql`
    select
      workspace.pitch,
      company.founded_year,
      role.request as legacy_request,
      internal_role.request as internal_request,
      role.opportunity_search_tsv @@ plainto_tsquery('simple', 'Backend') as search_updated
    from public.company_workspace workspace
    join public.company_db company on company.id = workspace.company_db_id
    join public.company_roles role on role.role_id = ${IDS.legacyRole}::uuid
    join public.company_internal_roles internal_role on internal_role.role_id = role.role_id
    where workspace.company_workspace_id = ${IDS.workspaceA}::uuid
  `
  );
  assert(
    state.pitch === "A concise company pitch",
    "workspace pitch was not updated"
  );
  assert(state.founded_year === 2021, "company_db field was not updated");
  assert(
    state.legacy_request === state.internal_request,
    "role request mirror drifted"
  );
  assert(
    state.search_updated === true,
    "legacy search vector did not observe the mirrored request"
  );
  assert(
    (await countEvents(sql)) === 1,
    "successful batch did not write exactly one event"
  );
  logPass(
    "apply RPC atomically updates flat fields, request mirror, search, and one event"
  );

  const noOpChanges = [
    {
      key: "pitch",
      role_id: null,
      expected: "A concise company pitch",
      value: "A concise company pitch",
    },
  ];
  const noOp = rpcResult(
    await sql`
    select public.apply_company_data_changes_v1(
      ${IDS.workspaceA}::uuid,
      ${JSON.stringify(noOpChanges)}::jsonb,
      'chat',
      'DB Tester · no-op'
    ) as result
  `
  );
  assert(
    noOp.status === "already_reflected",
    "no-op batch was not reported as already_reflected"
  );
  assert((await countEvents(sql)) === 1, "no-op batch wrote an event");
  logPass("apply RPC no-op does not create an event");

  const conflictChanges = [
    {
      key: "pitch",
      role_id: null,
      expected: "stale expected",
      value: "must not write",
    },
    { key: "founded_year", role_id: null, expected: 2021, value: 2022 },
  ];
  const conflict = rpcResult(
    await sql`
    select public.apply_company_data_changes_v1(
      ${IDS.workspaceA}::uuid,
      ${JSON.stringify(conflictChanges)}::jsonb,
      'website',
      'DB Tester · conflicting batch'
    ) as result
  `
  );
  assert(
    conflict.status === "conflict" && conflict.key === "pitch",
    "stale expected value was not rejected"
  );
  const afterConflict = firstRow(
    await sql`
    select workspace.pitch, company.founded_year
    from public.company_workspace workspace
    join public.company_db company on company.id = workspace.company_db_id
    where workspace.company_workspace_id = ${IDS.workspaceA}::uuid
  `
  );
  assert(
    afterConflict.pitch === "A concise company pitch" &&
      afterConflict.founded_year === 2021,
    "conflict batch partially wrote data"
  );
  assert((await countEvents(sql)) === 1, "conflict batch wrote an event");
  logPass("optimistic conflict aborts the entire batch without an event");

  const invalidChanges = [
    {
      key: "pitch",
      role_id: null,
      expected: "A concise company pitch",
      value: "would be a partial write",
    },
    {
      key: "role_request",
      role_id: IDS.legacyRole,
      expected: state.internal_request,
      value: "x".repeat(20_001),
    },
  ];
  await expectDbError(
    "invalid atomic batch",
    () => sql`
      select public.apply_company_data_changes_v1(
        ${IDS.workspaceA}::uuid,
        ${JSON.stringify(invalidChanges)}::jsonb,
        'chat',
        'DB Tester · invalid batch'
      )
    `,
    /role_request exceeds 20000 characters/i
  );
  const pitchAfterError = value<string>(
    await sql`
    select pitch from public.company_workspace
    where company_workspace_id = ${IDS.workspaceA}::uuid
  `,
    "pitch"
  );
  assert(
    pitchAfterError === "A concise company pitch",
    "validation error left a partial write"
  );
  assert((await countEvents(sql)) === 1, "validation error wrote an event");
  logPass("validation errors roll back every target in the batch");

  await expectDbError(
    "shared company_db guard",
    () => sql`
      insert into public.company_workspace(company_db_id, company_name)
      select company_db_id, 'Shared Mirror'
      from public.company_workspace
      where company_workspace_id = ${IDS.workspaceA}::uuid
    `,
    /company_workspace_company_db_id_uidx|duplicate key/i
  );
  logPass("company_db mirror cannot be shared by two workspaces");

  await sql`
    update public.company_workspace
    set company_description = null
    where company_workspace_id = ${IDS.workspaceA}::uuid
  `;
  await sql`
    update public.company_db company
    set description = 'Database fallback description'
    from public.company_workspace workspace
    where workspace.company_workspace_id = ${IDS.workspaceA}::uuid
      and company.id = workspace.company_db_id
  `;
  const mirrorEventsBefore = await countEvents(sql);
  const mirroredChanges = [
    {
      key: "company_description",
      expected_physical: {
        workspace: null,
        company_db: "Database fallback description",
      },
      value: "Unified company description",
    },
  ];
  const mirrored = rpcResult(
    await sql`
    select public.apply_company_data_changes_v1(
      ${IDS.workspaceA}::uuid,
      ${JSON.stringify(mirroredChanges)}::jsonb,
      'chat',
      'DB Tester · company description 통합'
    ) as result
  `
  );
  assert(
    mirrored.status === "updated" && mirrored.changed_count === 1,
    "mirrored fallback rewrite was not applied"
  );
  const mirroredState = firstRow(
    await sql`
    select workspace.company_description as workspace_value,
           company.description as company_db_value
    from public.company_workspace workspace
    join public.company_db company on company.id = workspace.company_db_id
    where workspace.company_workspace_id = ${IDS.workspaceA}::uuid
  `
  );
  assert(
    mirroredState.workspace_value === "Unified company description" &&
      mirroredState.company_db_value === "Unified company description",
    "mirrored rewrite did not converge workspace and company_db"
  );
  assert(
    (await countEvents(sql)) === mirrorEventsBefore + 1,
    "mirrored rewrite did not create exactly one event"
  );

  const repeatedMirrorChanges = [
    {
      key: "company_description",
      expected_physical: {
        workspace: "Unified company description",
        company_db: "Unified company description",
      },
      value: "Unified company description",
    },
  ];
  const repeatedMirror = rpcResult(
    await sql`
    select public.apply_company_data_changes_v1(
      ${IDS.workspaceA}::uuid,
      ${JSON.stringify(repeatedMirrorChanges)}::jsonb,
      'chat',
      'DB Tester · company description no-op'
    ) as result
  `
  );
  assert(
    repeatedMirror.status === "already_reflected",
    "idempotent mirrored rewrite was not a no-op"
  );
  assert(
    (await countEvents(sql)) === mirrorEventsBefore + 1,
    "idempotent mirrored rewrite created another event"
  );
  logPass(
    "mirrored workspace/company_db fallback rewrite converges and repeats idempotently"
  );

  const hiddenEventsBefore = await countEvents(sql);
  const convertedRequest = [
    "## Hard constraints",
    "",
    "- Production backend experience",
    "",
    "## Preferred criteria",
    "",
    "- B2B SaaS experience",
  ].join("\n");
  const hiddenChanges = [
    {
      key: "workspace_published_name",
      role_id: null,
      expected: null,
      value: "Acme Careers",
    },
    {
      key: "role_source_type",
      role_id: IDS.externalRole,
      expected: "external",
      value: "internal",
    },
    {
      key: "role_request",
      role_id: IDS.externalRole,
      expected: "external request",
      value: convertedRequest,
    },
    {
      key: "role_description_summary",
      role_id: IDS.externalRole,
      expected: null,
      value: "Short indexed role summary",
    },
    {
      key: "role_source_provider",
      role_id: IDS.externalRole,
      expected: null,
      value: "example-provider",
    },
    {
      key: "role_source_job_id",
      role_id: IDS.externalRole,
      expected: null,
      value: "job-123",
    },
    {
      key: "role_posted_at",
      role_id: IDS.externalRole,
      expected: null,
      value: "2026-08-01T00:00:00Z",
    },
    {
      key: "role_expires_at",
      role_id: IDS.externalRole,
      expected: null,
      value: "2026-09-01T00:00:00Z",
    },
  ];
  const hiddenApplied = rpcResult(
    await sql`
    select public.apply_company_data_changes_v1(
      ${IDS.workspaceA}::uuid,
      ${JSON.stringify(hiddenChanges)}::jsonb,
      'website',
      'DB Tester · external role 원자 전환'
    ) as result
  `
  );
  assert(
    hiddenApplied.status === "updated" && hiddenApplied.changed_count === 8,
    "website hidden-key conversion batch was not fully applied"
  );
  const hiddenState = firstRow(
    await sql`
    select workspace.published_name,
           role.source_type,
           role.description_summary,
           role.source_provider,
           role.source_job_id,
           to_char(role.posted_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') as posted_at,
           to_char(role.expires_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') as expires_at,
           role.request as legacy_request,
           internal_role.request as internal_request
    from public.company_workspace workspace
    join public.company_roles role on role.role_id = ${IDS.externalRole}::uuid
    join public.company_internal_roles internal_role on internal_role.role_id = role.role_id
    where workspace.company_workspace_id = ${IDS.workspaceA}::uuid
  `
  );
  assert(
    hiddenState.published_name === "Acme Careers" &&
      hiddenState.source_type === "internal" &&
      hiddenState.description_summary === "Short indexed role summary" &&
      hiddenState.source_provider === "example-provider" &&
      hiddenState.source_job_id === "job-123" &&
      hiddenState.posted_at === "2026-08-01T00:00:00Z" &&
      hiddenState.expires_at === "2026-09-01T00:00:00Z" &&
      hiddenState.legacy_request === convertedRequest &&
      hiddenState.internal_request === convertedRequest,
    "external role conversion did not converge source, request, and site metadata"
  );
  assert(
    (await countEvents(sql)) === hiddenEventsBefore + 1,
    "website conversion batch did not create exactly one event"
  );
  logPass(
    "website-only role conversion, request, and site metadata commit atomically"
  );

  const equivalentTimestampEventsBefore = await countEvents(sql);
  const canonicalPostedAt = value<string>(
    await sql`
      select public.company_data_change_current_value_v1(
        ${IDS.workspaceA}::uuid,
        'role_posted_at',
        ${IDS.externalRole}::uuid
      ) #>> '{}' as posted_at
    `,
    "posted_at"
  );
  const equivalentTimestampResult = rpcResult(
    await sql`
      select public.apply_company_data_changes_v1(
        ${IDS.workspaceA}::uuid,
        ${JSON.stringify([
          {
            key: "role_posted_at",
            role_id: IDS.externalRole,
            expected: "2026-08-01T09:00:00+09:00",
            value: "2026-08-01T00:00:00.000Z",
          },
        ])}::jsonb,
        'website',
        'DB Tester · equivalent timestamp'
      ) as result
    `
  );
  assert(
    canonicalPostedAt === "2026-08-01T00:00:00.000Z" &&
      equivalentTimestampResult.status === "already_reflected" &&
      equivalentTimestampResult.changed_count === 0 &&
      (await countEvents(sql)) === equivalentTimestampEventsBefore,
    "equivalent timestamp offsets created a false change or event"
  );
  logPass("role timestamps compare by canonical millisecond instant");

  const hiddenConflictChanges = [
    {
      key: "workspace_published_name",
      role_id: null,
      expected: "stale published name",
      value: "Must not write",
    },
    {
      key: "role_source_job_id",
      role_id: IDS.externalRole,
      expected: "job-123",
      value: "job-456",
    },
  ];
  const hiddenConflict = rpcResult(
    await sql`
    select public.apply_company_data_changes_v1(
      ${IDS.workspaceA}::uuid,
      ${JSON.stringify(hiddenConflictChanges)}::jsonb,
      'website',
      'DB Tester · hidden conflict'
    ) as result
  `
  );
  assert(
    hiddenConflict.status === "conflict" &&
      hiddenConflict.key === "workspace_published_name",
    "hidden-key optimistic conflict was not returned"
  );
  const hiddenAfterConflict = firstRow(
    await sql`
    select workspace.published_name, role.source_job_id
    from public.company_workspace workspace
    join public.company_roles role on role.role_id = ${IDS.externalRole}::uuid
    where workspace.company_workspace_id = ${IDS.workspaceA}::uuid
  `
  );
  assert(
    hiddenAfterConflict.published_name === "Acme Careers" &&
      hiddenAfterConflict.source_job_id === "job-123" &&
      (await countEvents(sql)) === hiddenEventsBefore + 1,
    "hidden-key conflict partially wrote data or an event"
  );

  const invalidCatalogCases: Array<{
    change: Record<string, unknown>;
    label: string;
    pattern: RegExp;
    source?: "chat" | "website";
  }> = [
    {
      change: {
        key: "workspace_published_name",
        role_id: null,
        expected: "Acme Careers",
        value: "Chat cannot write this",
      },
      label: "hidden key from chat",
      pattern: /only available to website mutations/i,
      source: "chat",
    },
    {
      change: {
        key: "role_status",
        role_id: IDS.legacyRole,
        expected: "active",
        value: "invented_status",
      },
      label: "role status allowlist",
      pattern: /invalid role status/i,
    },
    {
      change: {
        key: "homepage_url",
        role_id: null,
        expected_physical: { workspace: null, company_db: null },
        value: "javascript:alert(1)",
      },
      label: "URL protocol",
      pattern: /valid http\(s\) URL/i,
    },
    {
      change: {
        key: "founded_year",
        role_id: null,
        expected: 2021,
        value: -1,
      },
      label: "nonnegative integer",
      pattern: /non-negative 32-bit integer/i,
    },
    {
      change: {
        key: "role_employment_types",
        role_id: IDS.legacyRole,
        expected: [],
        value: ["full_time", "freelance"],
      },
      label: "employment type allowlist",
      pattern: /invalid role employment type/i,
    },
    {
      change: {
        key: "company_description",
        role_id: null,
        expected_physical: {
          workspace: "Unified company description",
          company_db: "Unified company description",
        },
        value: "x".repeat(8_001),
      },
      label: "catalog text max length",
      pattern: /exceeds its maximum length/i,
    },
  ];
  for (const invalid of invalidCatalogCases) {
    await expectDbError(
      invalid.label,
      () => sql`
        select public.apply_company_data_changes_v1(
          ${IDS.workspaceA}::uuid,
          ${JSON.stringify([invalid.change])}::jsonb,
          ${invalid.source ?? "website"},
          'DB Tester · invalid catalog value'
        )
      `,
      invalid.pattern
    );
  }
  assert(
    (await countEvents(sql)) === hiddenEventsBefore + 1,
    "catalog validation failure wrote an event"
  );
  logPass(
    "SECURITY DEFINER value validation matches enum, URL, size, and integer contracts"
  );

  const sourceTransitionEventsBefore = await countEvents(sql);
  const canonicalBeforeExternalization =
    "Canonical request despite a stale legacy mirror";
  await sql`
    update public.company_internal_roles
    set request = ${canonicalBeforeExternalization}
    where role_id = ${IDS.externalRole}::uuid
  `;
  const externalRequest = "Website-owned external request";
  const externalizedBatch = rpcResult(
    await sql`
      select public.apply_company_data_changes_v1(
        ${IDS.workspaceA}::uuid,
        ${JSON.stringify([
          {
            key: "role_source_type",
            role_id: IDS.externalRole,
            expected: "internal",
            value: "external",
          },
          {
            key: "role_request",
            role_id: IDS.externalRole,
            expected: canonicalBeforeExternalization,
            value: externalRequest,
          },
        ])}::jsonb,
        'website',
        'DB Tester · role externalization'
      ) as result
    `
  );
  const externalizedState = firstRow(
    await sql`
      select role.source_type, role.request,
             exists (
               select 1 from public.company_internal_roles internal_role
               where internal_role.role_id = role.role_id
             ) as has_extension
      from public.company_roles role
      where role.role_id = ${IDS.externalRole}::uuid
    `
  );
  assert(
    externalizedBatch.status === "updated" &&
      externalizedBatch.changed_count === 2 &&
      externalizedState.source_type === "external" &&
      externalizedState.request === externalRequest &&
      externalizedState.has_extension === false,
    "internal to external batch lost the revised legacy request or retained its extension"
  );

  await expectDbError(
    "chat cannot edit an external role request",
    () => sql`
      select public.apply_company_data_changes_v1(
        ${IDS.workspaceA}::uuid,
        ${JSON.stringify([
          {
            key: "role_request",
            role_id: IDS.externalRole,
            expected: externalRequest,
            value: "Chat must not write this",
          },
        ])}::jsonb,
        'chat',
        'DB Tester · invalid external chat request'
      )
    `,
    /final active internal role/i
  );

  const revisedExternalRequest = "Revised website external request";
  const revisedExternal = rpcResult(
    await sql`
      select public.apply_company_data_changes_v1(
        ${IDS.workspaceA}::uuid,
        ${JSON.stringify([
          {
            key: "role_request",
            role_id: IDS.externalRole,
            expected: externalRequest,
            value: revisedExternalRequest,
          },
        ])}::jsonb,
        'website',
        'DB Tester · external request edit'
      ) as result
    `
  );
  assert(
    revisedExternal.status === "updated" && revisedExternal.changed_count === 1,
    "stable external website request update failed"
  );

  const reinternalizedRequest = "Reinternalized canonical request";
  const reinternalizedBatch = rpcResult(
    await sql`
      select public.apply_company_data_changes_v1(
        ${IDS.workspaceA}::uuid,
        ${JSON.stringify([
          {
            key: "role_source_type",
            role_id: IDS.externalRole,
            expected: "external",
            value: "internal",
          },
          {
            key: "role_request",
            role_id: IDS.externalRole,
            expected: revisedExternalRequest,
            value: reinternalizedRequest,
          },
        ])}::jsonb,
        'website',
        'DB Tester · role reinternalization'
      ) as result
    `
  );
  const reinternalizedState = firstRow(
    await sql`
      select role.source_type,
             role.request as legacy_request,
             internal_role.request as internal_request
      from public.company_roles role
      join public.company_internal_roles internal_role
        on internal_role.role_id = role.role_id
      where role.role_id = ${IDS.externalRole}::uuid
    `
  );
  assert(
    reinternalizedBatch.status === "updated" &&
      reinternalizedBatch.changed_count === 2 &&
      reinternalizedState.source_type === "internal" &&
      reinternalizedState.legacy_request === reinternalizedRequest &&
      reinternalizedState.internal_request === reinternalizedRequest &&
      (await countEvents(sql)) === sourceTransitionEventsBefore + 3,
    "external to internal batch did not seed and revise the canonical request atomically"
  );
  logPass(
    "website role request semantics follow final source across both transition directions"
  );

  const originalCompanyDbId = Number(
    value<number>(
      await sql`
        select company_db_id::integer as company_db_id
        from public.company_workspace
        where company_workspace_id = ${IDS.workspaceA}::uuid
      `,
      "company_db_id"
    )
  );
  const targetCompanyDb = firstRow(
    await sql`
    insert into public.company_db(name, linkedin_url, logo, website_url, specialities)
    values (
      'Target company mirror',
      'https://www.linkedin.com/company/acme-target',
      'https://cdn.example.com/acme-target.png',
      'https://target.example.com',
      ''
    )
    returning id
  `
  );
  const targetCompanyDbId = Number(targetCompanyDb.id);
  const reassociationEventsBefore = await countEvents(sql);
  const reassociationChanges = [
    {
      key: "linkedin_url",
      role_id: null,
      expected_physical: {
        workspace: null,
        company_db: "https://www.linkedin.com/company/acme-target",
      },
      value: "https://www.linkedin.com/company/acme-target",
    },
    {
      key: "logo_url",
      role_id: null,
      expected_physical: {
        workspace: null,
        company_db: "https://cdn.example.com/acme-target.png",
      },
      value: "https://cdn.example.com/acme-target.png",
    },
  ];
  const reassociated = rpcResult(
    await sql`
    select public.reassociate_company_workspace_db_v1(
      ${IDS.workspaceA}::uuid,
      ${originalCompanyDbId},
      ${targetCompanyDbId},
      ${JSON.stringify(reassociationChanges)}::jsonb,
      'DB Tester · LinkedIn 회사 연결 변경'
    ) as result
  `
  );
  assert(
    reassociated.status === "updated" &&
      reassociated.reassociated === true &&
      reassociated.changed_count === 3,
    "company_db reassociation and flat mirrors were not committed together"
  );
  const reassociatedState = firstRow(
    await sql`
    select workspace.company_db_id,
           workspace.linkedin_url,
           workspace.logo_url,
           company.linkedin_url as company_linkedin_url,
           company.logo as company_logo
    from public.company_workspace workspace
    join public.company_db company on company.id = workspace.company_db_id
    where workspace.company_workspace_id = ${IDS.workspaceA}::uuid
  `
  );
  assert(
    Number(reassociatedState.company_db_id) === targetCompanyDbId &&
      reassociatedState.linkedin_url ===
        "https://www.linkedin.com/company/acme-target" &&
      reassociatedState.logo_url ===
        "https://cdn.example.com/acme-target.png" &&
      reassociatedState.company_linkedin_url ===
        reassociatedState.linkedin_url &&
      reassociatedState.company_logo === reassociatedState.logo_url &&
      (await countEvents(sql)) === reassociationEventsBefore + 1,
    "reassociation did not persist target and mirrors with one event"
  );
  logPass("company_db reassociation, mirrored values, and event are atomic");

  const alternateCompanyDb = firstRow(
    await sql`
    insert into public.company_db(name, linkedin_url, logo, website_url, specialities)
    values (
      'Alternate target',
      'https://www.linkedin.com/company/acme-alternate',
      'https://cdn.example.com/acme-alternate.png',
      'https://alternate.example.com',
      ''
    )
    returning id
  `
  );
  const alternateCompanyDbId = Number(alternateCompanyDb.id);
  const flatConflictChanges = [
    {
      key: "linkedin_url",
      role_id: null,
      expected_physical: {
        workspace: "https://stale.example.com/company",
        company_db: "https://www.linkedin.com/company/acme-alternate",
      },
      value: "https://www.linkedin.com/company/acme-alternate",
    },
  ];
  const reassociationConflict = rpcResult(
    await sql`
    select public.reassociate_company_workspace_db_v1(
      ${IDS.workspaceA}::uuid,
      ${targetCompanyDbId},
      ${alternateCompanyDbId},
      ${JSON.stringify(flatConflictChanges)}::jsonb,
      'DB Tester · stale LinkedIn reassociation'
    ) as result
  `
  );
  assert(
    reassociationConflict.status === "conflict" &&
      reassociationConflict.association_rolled_back === true,
    "flat conflict did not report a rolled-back reassociation"
  );
  let associationAfterFailure = Number(
    value<number>(
      await sql`
        select company_db_id::integer as company_db_id
        from public.company_workspace
        where company_workspace_id = ${IDS.workspaceA}::uuid
      `,
      "company_db_id"
    )
  );
  assert(
    associationAfterFailure === targetCompanyDbId &&
      (await countEvents(sql)) === reassociationEventsBefore + 1,
    "flat conflict changed company_db association or wrote an event"
  );

  await expectDbError(
    "invalid flat value rolls back reassociation",
    () => sql`
      select public.reassociate_company_workspace_db_v1(
        ${IDS.workspaceA}::uuid,
        ${targetCompanyDbId},
        ${alternateCompanyDbId},
        ${JSON.stringify([
          {
            key: "homepage_url",
            role_id: null,
            expected_physical: {
              workspace: null,
              company_db: "https://alternate.example.com",
            },
            value: "file:///etc/passwd",
          },
        ])}::jsonb,
        'DB Tester · invalid reassociation'
      )
    `,
    /valid http\(s\) URL/i
  );
  associationAfterFailure = Number(
    value<number>(
      await sql`
        select company_db_id::integer as company_db_id
        from public.company_workspace
        where company_workspace_id = ${IDS.workspaceA}::uuid
      `,
      "company_db_id"
    )
  );
  assert(
    associationAfterFailure === targetCompanyDbId &&
      (await countEvents(sql)) === reassociationEventsBefore + 1,
    "validation error changed company_db association or wrote an event"
  );

  const duplicateTarget = rpcResult(
    await sql`
    select public.reassociate_company_workspace_db_v1(
      ${IDS.workspaceB}::uuid,
      null,
      ${targetCompanyDbId},
      ${JSON.stringify([
        {
          key: "company_name",
          role_id: null,
          expected_physical: {
            workspace: "Other Co",
            company_db: "Target company mirror",
          },
          value: "Other Co",
        },
      ])}::jsonb,
      'DB Tester · duplicate company target'
    ) as result
  `
  );
  assert(
    duplicateTarget.status === "conflict" &&
      duplicateTarget.key === "target_company_db_id",
    "duplicate target company_db association was not rejected"
  );
  assert(
    value<number | null>(
      await sql`
        select company_db_id from public.company_workspace
        where company_workspace_id = ${IDS.workspaceB}::uuid
      `,
      "company_db_id"
    ) === null && (await countEvents(sql)) === reassociationEventsBefore + 1,
    "duplicate target rejection changed workspace B or wrote an event"
  );
  logPass(
    "reassociation expected, target, flat, and validation failures fully roll back"
  );

  const detachmentEventsBefore = await countEvents(sql);
  const companyDbRowsBeforeDetach = Number(
    value<number>(
      await sql`select count(*)::integer as count from public.company_db`,
      "count"
    )
  );
  await expectDbError(
    "detached company_db-only value is rejected atomically",
    () => sql`
      select public.reassociate_company_workspace_db_v1(
        ${IDS.workspaceA}::uuid,
        ${targetCompanyDbId},
        null,
        ${JSON.stringify([
          {
            key: "location",
            role_id: null,
            expected: null,
            value: "Seoul",
          },
        ])}::jsonb,
        'DB Tester · invalid detached company data'
      )
    `,
    /requires a target company_db row/i
  );
  assert(
    Number(
      value<number>(
        await sql`
          select company_db_id::integer as company_db_id
          from public.company_workspace
          where company_workspace_id = ${IDS.workspaceA}::uuid
        `,
        "company_db_id"
      )
    ) === targetCompanyDbId &&
      Number(
        value<number>(
          await sql`select count(*)::integer as count from public.company_db`,
          "count"
        )
      ) === companyDbRowsBeforeDetach &&
      (await countEvents(sql)) === detachmentEventsBefore,
    "invalid detached company_db-only update changed association, rows, or events"
  );

  const detachedChanges = [
    {
      key: "linkedin_url",
      role_id: null,
      expected_physical: {
        workspace: "https://www.linkedin.com/company/acme-target",
        company_db: null,
      },
      value: null,
    },
    {
      key: "logo_url",
      role_id: null,
      expected_physical: {
        workspace: "https://cdn.example.com/acme-target.png",
        company_db: null,
      },
      value: null,
    },
  ];
  const detached = rpcResult(
    await sql`
      select public.reassociate_company_workspace_db_v1(
        ${IDS.workspaceA}::uuid,
        ${targetCompanyDbId},
        null,
        ${JSON.stringify(detachedChanges)}::jsonb,
        'DB Tester · LinkedIn 회사 연결 해제'
      ) as result
    `
  );
  const detachedState = firstRow(
    await sql`
      select workspace.company_db_id,
             workspace.linkedin_url,
             workspace.logo_url,
             target.linkedin_url as old_linkedin_url,
             target.logo as old_logo
      from public.company_workspace workspace
      join public.company_db target on target.id = ${targetCompanyDbId}
      where workspace.company_workspace_id = ${IDS.workspaceA}::uuid
    `
  );
  assert(
    detached.status === "updated" &&
      detached.reassociated === true &&
      detached.changed_count === 3 &&
      detachedState.company_db_id === null &&
      detachedState.linkedin_url === null &&
      detachedState.logo_url === null &&
      detachedState.old_linkedin_url ===
        "https://www.linkedin.com/company/acme-target" &&
      detachedState.old_logo === "https://cdn.example.com/acme-target.png" &&
      (await countEvents(sql)) === detachmentEventsBefore + 1,
    "company_db detachment created a replacement row, changed the old row, or split its event"
  );

  const repeatedDetach = rpcResult(
    await sql`
      select public.reassociate_company_workspace_db_v1(
        ${IDS.workspaceA}::uuid,
        null,
        null,
        ${JSON.stringify(
          detachedChanges.map((change) => ({
            ...change,
            expected_physical: { company_db: null, workspace: null },
          }))
        )}::jsonb,
        'DB Tester · repeated company detach'
      ) as result
    `
  );
  assert(
    repeatedDetach.status === "already_reflected" &&
      repeatedDetach.reassociated === false &&
      repeatedDetach.changed_count === 0 &&
      (await countEvents(sql)) === detachmentEventsBefore + 1,
    "idempotent company_db detachment created an event or mirror row"
  );

  const associationOnly = rpcResult(
    await sql`
      select public.reassociate_company_workspace_db_v1(
        ${IDS.workspaceA}::uuid,
        null,
        ${alternateCompanyDbId},
        '[]'::jsonb,
        'DB Tester · association only'
      ) as result
    `
  );
  assert(
    associationOnly.status === "updated" &&
      associationOnly.reassociated === true &&
      associationOnly.changed_count === 1 &&
      Number(
        value<number>(
          await sql`
            select company_db_id::integer as company_db_id
            from public.company_workspace
            where company_workspace_id = ${IDS.workspaceA}::uuid
          `,
          "company_db_id"
        )
      ) === alternateCompanyDbId &&
      (await countEvents(sql)) === detachmentEventsBefore + 2,
    "association-only update did not atomically link the target with one event"
  );
  logPass(
    "company_db attach, detach, and association-only paths preserve mirror and event semantics"
  );

  let lockOrderTransactionOpen = false;
  let conflictSettled = false;
  let conflictOutcomePromise:
    | Promise<{
        error?: unknown;
        result?: Record<string, unknown>;
      }>
    | undefined;
  try {
    await lockHolder.unsafe("begin");
    lockOrderTransactionOpen = true;
    await lockHolder`
      select company_workspace_id
      from public.company_workspace
      where company_workspace_id = ${IDS.workspaceA}::uuid
      for update
    `;

    conflictOutcomePromise = (async () => {
      try {
        return {
          result: rpcResult(
            await sql`
              select public.reassociate_company_workspace_db_v1(
                ${IDS.workspaceB}::uuid,
                null,
                ${alternateCompanyDbId},
                '[]'::jsonb,
                'DB Tester · lock-order conflict'
              ) as result
            `
          ),
        };
      } catch (error) {
        return { error };
      } finally {
        conflictSettled = true;
      }
    })();

    let conflictQueryObserved = false;
    for (let attempt = 0; attempt < 50 && !conflictSettled; attempt += 1) {
      const activity = await lockHolder`
        select pid
        from pg_stat_activity
        where datname = current_database()
          and pid <> pg_backend_pid()
          and query like '%lock-order conflict%'
      `;
      if (activity.length > 0) {
        conflictQueryObserved = true;
        break;
      }
      await new Promise<void>((resolve) => setTimeout(resolve, 10));
    }
    assert(
      conflictSettled || conflictQueryObserved,
      "reassociation lock-order query did not start"
    );

    await lockHolder.unsafe("set local lock_timeout = '750ms'");
    await lockHolder`
      select id
      from public.company_db
      where id = ${alternateCompanyDbId}
      for update
    `;
    await lockHolder.unsafe("commit");
    lockOrderTransactionOpen = false;

    const conflictOutcome = await conflictOutcomePromise;
    if (conflictOutcome.error) throw conflictOutcome.error;
    assert(
      conflictOutcome.result?.status === "conflict" &&
        conflictOutcome.result.key === "target_company_db_id" &&
        conflictOutcome.result.conflicting_workspace_id === IDS.workspaceA,
      "concurrent conflicting reassociation did not return the existing workspace"
    );
    assert(
      value<number | null>(
        await sql`
          select company_db_id
          from public.company_workspace
          where company_workspace_id = ${IDS.workspaceB}::uuid
        `,
        "company_db_id"
      ) === null,
      "lock-order conflict changed the source workspace association"
    );
    logPass(
      "reassociation conflict does not invert ordinary workspace-to-company_db lock order"
    );
  } finally {
    if (lockOrderTransactionOpen) {
      await lockHolder.unsafe("rollback").catch(() => undefined);
    }
    if (conflictOutcomePromise) {
      await conflictOutcomePromise.catch(() => undefined);
    }
  }
}

async function insertUserMessage(
  sql: Db,
  args: {
    content: string;
    messageType?: "chat" | "slack";
    slackMessageTs?: string;
    slackThreadId?: string;
    slackUserId?: string;
  }
) {
  const row = firstRow(
    await sql`
    insert into public.company_messages(
      conversation_id, company_workspace_id, company_user_id, role, content,
      message_type, slack_thread_id, slack_message_ts, slack_user_id
    ) values (
      ${IDS.conversation}::uuid,
      ${IDS.workspaceA}::uuid,
      ${IDS.user}::uuid,
      'user',
      ${args.content},
      ${args.messageType ?? "chat"},
      ${args.slackThreadId ?? null}::uuid,
      ${args.slackMessageTs ?? null},
      ${args.slackUserId ?? null}
    )
    returning id
  `
  );
  return Number(row.id);
}

async function presentChatProposal(
  sql: Db,
  args: {
    changes: unknown[];
    eventContent: string;
    preview: string;
    presentationText: string;
    summary: string;
    userMessageId: number;
  }
) {
  return rpcResult(
    await sql`
    select public.present_company_agent_update_proposal_v1(
      ${IDS.workspaceA}::uuid,
      ${`chat:${IDS.conversation}`},
      'chat',
      ${args.userMessageId},
      ${args.summary},
      ${args.preview},
      ${JSON.stringify({ changes: args.changes, event_content: args.eventContent })}::jsonb,
      ${args.presentationText},
      null,
      ${JSON.stringify({ llmUsage: { inputTokens: 10 }, retainedDataActivations: ["company_details"] })}::jsonb,
      'test-model',
      ${JSON.stringify([{ type: "summary", content: "test thinking" }])}::jsonb,
      'chat'
    ) as result
  `
  );
}

async function resolveProposal(
  sql: Db,
  args: {
    action: "apply" | "reject" | "preview";
    currentUserMessageId: number;
    proposalId: string;
    scopeKey: string;
  }
) {
  return rpcResult(
    await sql`
    select public.resolve_company_agent_update_proposal_v1(
      ${IDS.workspaceA}::uuid,
      ${args.scopeKey},
      ${args.currentUserMessageId},
      ${args.proposalId}::uuid,
      ${args.action}
    ) as result
  `
  );
}

async function testChatProposalLifecycle(sql: Db) {
  await sql`
    insert into public.company_conversations(id, company_workspace_id, metadata)
    values (${IDS.conversation}::uuid, ${IDS.workspaceA}::uuid, '{"scope":"workspace"}'::jsonb)
  `;
  const currentRequest = value<string>(
    await sql`
    select request from public.company_internal_roles
    where role_id = ${IDS.legacyRole}::uuid
  `,
    "request"
  );
  const finalRequest = `${currentRequest}\n- PostgreSQL experience`;
  const requestUserMessageId = await insertUserMessage(sql, {
    content: "PostgreSQL 경험을 우대 조건에 저장해줘",
  });
  const presented = await presentChatProposal(sql, {
    changes: [
      {
        key: "role_request",
        role_id: IDS.legacyRole,
        expected: currentRequest,
        value: finalRequest,
      },
    ],
    eventContent: "DB Tester · Legacy Role 우대 조건 수정",
    preview: "+ PostgreSQL experience",
    presentationText:
      "Legacy Role 기준에 PostgreSQL 경험을 추가할까요?\n\n+ PostgreSQL experience",
    summary: "Legacy Role 우대 조건 수정",
    userMessageId: requestUserMessageId,
  });
  assert(presented.status === "pending", "chat proposal was not made pending");
  const proposalId = String(presented.proposal_id);
  const presentedMessageId = Number(presented.presented_message_id);
  const assistant = firstRow(
    await sql`
    select model, message_type, metadata, thinking_logs
    from public.company_messages
    where id = ${presentedMessageId}
  `
  );
  const metadata = assistant.metadata as Record<string, unknown>;
  const ref = metadata.updateProposalRef as Record<string, unknown>;
  assert(
    ref.proposalId === proposalId,
    "chat assistant message is missing its proposal ref"
  );
  assert(
    assistant.model === "test-model" && assistant.message_type === "chat",
    "chat proposal lost model or message type"
  );
  assert(
    Array.isArray(assistant.thinking_logs) &&
      assistant.thinking_logs.length === 1,
    "chat proposal lost thinking logs"
  );
  assert(
    metadata.llmUsage !== undefined,
    "chat proposal lost message metadata"
  );

  const confirmMessageId = await insertUserMessage(sql, { content: "응" });
  const applied = await resolveProposal(sql, {
    action: "apply",
    currentUserMessageId: confirmMessageId,
    proposalId,
    scopeKey: `chat:${IDS.conversation}`,
  });
  assert(
    applied.status === "applied",
    "confirmed chat proposal was not applied"
  );
  const appliedState = firstRow(
    await sql`
    select
      proposal.status,
      proposal.payload,
      role.request as legacy,
      internal_role.request as internal
    from public.company_agent_update_proposals proposal
    join public.company_roles role on role.role_id = ${IDS.legacyRole}::uuid
    join public.company_internal_roles internal_role on internal_role.role_id = role.role_id
    where proposal.id = ${proposalId}::uuid
  `
  );
  assert(
    appliedState.status === "applied" && appliedState.payload === null,
    "applied proposal retained its exact payload"
  );
  assert(
    appliedState.legacy === finalRequest &&
      appliedState.internal === finalRequest,
    "proposal apply did not mirror request"
  );
  logPass(
    "chat proposal preserves message metadata and applies exact stored changes once"
  );

  const rejectUserMessageId = await insertUserMessage(sql, {
    content: "회사 메모에 저장해줘",
  });
  const rejectedProposal = await presentChatProposal(sql, {
    changes: [
      {
        key: "workspace_memory",
        role_id: null,
        expected: null,
        value: "Do not persist this",
      },
    ],
    eventContent: "DB Tester · workspace memory 수정",
    preview: "+ Do not persist this",
    presentationText:
      "회사 메모에 이 내용을 저장할까요?\n\n+ Do not persist this",
    summary: "workspace memory 수정",
    userMessageId: rejectUserMessageId,
  });
  const rejectReplyId = await insertUserMessage(sql, { content: "아니" });
  const rejected = await resolveProposal(sql, {
    action: "reject",
    currentUserMessageId: rejectReplyId,
    proposalId: String(rejectedProposal.proposal_id),
    scopeKey: `chat:${IDS.conversation}`,
  });
  assert(
    rejected.status === "rejected",
    "proposal rejection did not close the proposal"
  );
  const memoryCount = Number(
    value<number>(
      await sql`
    select count(*)::integer as count
    from public.company_memories
    where company_workspace_id = ${IDS.workspaceA}::uuid and role_id is null
  `,
      "count"
    )
  );
  assert(memoryCount === 0, "rejected proposal wrote workspace memory");
  logPass("rejected proposal writes neither data nor an event");

  const staleUserMessageId = await insertUserMessage(sql, {
    content: "pitch를 바꿔줘",
  });
  const staleProposal = await presentChatProposal(sql, {
    changes: [
      {
        key: "pitch",
        role_id: null,
        expected: "A concise company pitch",
        value: "Proposed pitch",
      },
    ],
    eventContent: "DB Tester · pitch 수정",
    preview: "- A concise company pitch\n+ Proposed pitch",
    presentationText: "pitch를 Proposed pitch로 바꿀까요?",
    summary: "pitch 수정",
    userMessageId: staleUserMessageId,
  });
  await sql`
    update public.company_workspace
    set pitch = 'Changed elsewhere'
    where company_workspace_id = ${IDS.workspaceA}::uuid
  `;
  const staleReplyId = await insertUserMessage(sql, { content: "응" });
  const beforeStaleEvents = await countEvents(sql);
  const stale = await resolveProposal(sql, {
    action: "apply",
    currentUserMessageId: staleReplyId,
    proposalId: String(staleProposal.proposal_id),
    scopeKey: `chat:${IDS.conversation}`,
  });
  assert(
    stale.status === "stale",
    "proposal expected-value conflict was not marked stale"
  );
  assert(
    (await countEvents(sql)) === beforeStaleEvents,
    "stale proposal wrote an event"
  );
  const stalePayload = firstRow(
    await sql`
    select status, payload from public.company_agent_update_proposals
    where id = ${String(staleProposal.proposal_id)}::uuid
  `
  );
  assert(
    stalePayload.status === "stale" && stalePayload.payload === null,
    "stale proposal retained exact payload"
  );
  logPass("stale proposal is consumed without partial data or an event");
}

async function ensureSlackFixtures(sql: Db) {
  await sql`
    insert into public.company_slack_integrations(company_workspace_id, slack_team_id)
    values (${IDS.workspaceA}::uuid, 'T_TEST')
    on conflict (company_workspace_id) do nothing
  `;
  await sql`
    insert into public.company_slack_channels(
      id, company_workspace_id, slack_team_id, slack_channel_id
    ) values (${IDS.slackChannel}::uuid, ${IDS.workspaceA}::uuid, 'T_TEST', 'C_TEST')
    on conflict (id) do nothing
  `;
  await sql`
    insert into public.company_slack_threads(id, channel_id, role_id, slack_thread_ts)
    values (${IDS.slackThread}::uuid, ${IDS.slackChannel}::uuid, null, '1700000000.000001')
    on conflict (id) do nothing
  `;
}

async function insertNormalSlackAssistant(
  sql: Db,
  args: {
    content: string;
    jobId: string;
    slackMessageTs?: string;
    source?: string;
  }
) {
  const row = firstRow(
    await sql`
    insert into public.company_messages(
      conversation_id, company_workspace_id, role, content, message_type,
      model, status, thinking_logs, metadata, slack_thread_id,
      slack_message_ts, slack_user_id
    ) values (
      ${IDS.conversation}::uuid, ${IDS.workspaceA}::uuid, 'assistant',
      ${args.content}, 'slack', 'test-slack-model', 'completed',
      '[{"type":"summary","content":"normal reply thinking"}]'::jsonb,
      ${JSON.stringify({
        slackReplyJobId: args.jobId,
        source: args.source ?? "org_agent_slack",
      })}::jsonb,
      ${IDS.slackThread}::uuid, ${args.slackMessageTs ?? null}, 'U_BOT'
    )
    returning id
  `
  );
  return Number(row.id);
}

async function finalizeSlackReply(
  sql: Db,
  args: { jobId: string; slackMessageTs: string }
) {
  return rpcResult(
    await sql`
    select public.finalize_slack_company_agent_reply_v1(
      ${args.jobId}::uuid,
      ${args.slackMessageTs},
      'U_BOT'
    ) as result
  `
  );
}

async function testSlackReplyFinalization(sql: Db) {
  await ensureSlackFixtures(sql);

  const normalContent = "Normal Slack response";
  const normalMessageId = await insertNormalSlackAssistant(sql, {
    content: normalContent,
    jobId: IDS.normalReplyJob,
  });
  await sql`
    insert into public.slack_reply_jobs(
      id, slack_event_id, thread_id, response_message_id, trigger_kind,
      slack_message_ts, prompt, status, locked_at, locked_by, response_text
    ) values (
      ${IDS.normalReplyJob}::uuid, 'Ev_NORMAL', ${IDS.slackThread}::uuid,
      ${normalMessageId}, 'mention', '1700000010.000001', 'normal prompt',
      'processing', now(), 'db-test-worker', ${normalContent}
    )
  `;
  const normal = await finalizeSlackReply(sql, {
    jobId: IDS.normalReplyJob,
    slackMessageTs: "1700000011.000001",
  });
  assert(
    normal.status === "completed" &&
      normal.adopted === false &&
      Number(normal.response_message_id) === normalMessageId,
    "normal Slack reply was not finalized on its persisted assistant"
  );
  const normalState = firstRow(
    await sql`
    select job.status, job.response_message_id, job.slack_response_ts,
           job.completed_at, job.updated_at, job.locked_at, job.locked_by,
           message.slack_message_ts as message_ts,
           message.metadata,
           thread.created_by_harper
    from public.slack_reply_jobs job
    join public.company_messages message on message.id = job.response_message_id
    join public.company_slack_threads thread on thread.id = job.thread_id
    where job.id = ${IDS.normalReplyJob}::uuid
  `
  );
  assert(
    normalState.status === "completed" &&
      normalState.slack_response_ts === "1700000011.000001" &&
      normalState.message_ts === "1700000011.000001" &&
      normalState.created_by_harper === true &&
      normalState.locked_at === null &&
      normalState.locked_by === null,
    "normal Slack finalization did not atomically complete message, thread, and job"
  );
  const normalMetadata = normalState.metadata as Record<string, unknown>;
  assert(
    normalMetadata.source === "company_side_llm" &&
      normalMetadata.slackReplyJobId === IDS.normalReplyJob,
    "normal Slack finalization did not normalize company-side message metadata"
  );

  const repeated = await finalizeSlackReply(sql, {
    jobId: IDS.normalReplyJob,
    slackMessageTs: "1700000011.000001",
  });
  const repeatedState = firstRow(
    await sql`
    select completed_at, updated_at
    from public.slack_reply_jobs
    where id = ${IDS.normalReplyJob}::uuid
  `
  );
  assert(
    repeated.status === "completed" && repeated.idempotent === true,
    "Slack finalization retry was not idempotent"
  );
  assert(
    repeatedState.completed_at === normalState.completed_at &&
      repeatedState.updated_at === normalState.updated_at,
    "idempotent Slack finalization rewrote completion timestamps"
  );
  logPass("normal Slack reply finalization is atomic and idempotent");

  const adoptedContent = "Thread sync won this delivery race";
  const redundantMessageId = await insertNormalSlackAssistant(sql, {
    content: adoptedContent,
    jobId: IDS.adoptedReplyJob,
  });
  const canonicalMessageId = await insertNormalSlackAssistant(sql, {
    content: adoptedContent,
    jobId: "thread-sync-placeholder",
    slackMessageTs: "1700000021.000001",
    source: "slack_thread_sync",
  });
  await sql`
    update public.company_messages
    set model = null,
        thinking_logs = '[]'::jsonb,
        metadata = '{"source":"slack_thread_sync"}'::jsonb
    where id = ${canonicalMessageId}
  `;
  await sql`
    update public.company_conversations
    set last_message_id = ${redundantMessageId}
    where id = ${IDS.conversation}::uuid
  `;
  await sql`
    insert into public.slack_reply_jobs(
      id, slack_event_id, thread_id, response_message_id, trigger_kind,
      slack_message_ts, prompt, status, locked_at, locked_by, response_text
    ) values (
      ${IDS.adoptedReplyJob}::uuid, 'Ev_ADOPT', ${IDS.slackThread}::uuid,
      ${redundantMessageId}, 'mention', '1700000020.000001', 'adopt prompt',
      'processing', now(), 'db-test-worker', ${adoptedContent}
    )
  `;
  const adopted = await finalizeSlackReply(sql, {
    jobId: IDS.adoptedReplyJob,
    slackMessageTs: "1700000021.000001",
  });
  assert(
    adopted.status === "completed" &&
      adopted.adopted === true &&
      Number(adopted.response_message_id) === canonicalMessageId,
    "thread-sync winner was not adopted as the canonical Slack message"
  );
  const adoptedState = firstRow(
    await sql`
    select job.response_message_id,
           conversation.last_message_id,
           canonical.metadata,
           canonical.model,
           canonical.thinking_logs,
           exists(
             select 1 from public.company_messages redundant
             where redundant.id = ${redundantMessageId}
           ) as redundant_exists
    from public.slack_reply_jobs job
    join public.company_messages canonical on canonical.id = job.response_message_id
    join public.company_conversations conversation
      on conversation.id = canonical.conversation_id
    where job.id = ${IDS.adoptedReplyJob}::uuid
  `
  );
  const adoptedMetadata = adoptedState.metadata as Record<string, unknown>;
  assert(
    Number(adoptedState.response_message_id) === canonicalMessageId &&
      Number(adoptedState.last_message_id) === canonicalMessageId &&
      adoptedState.redundant_exists === false,
    "adopted Slack reply did not repoint job/conversation and delete redundant A"
  );
  assert(
    adoptedMetadata.slackReplyJobId === IDS.adoptedReplyJob &&
      adoptedMetadata.source === "company_side_llm" &&
      adoptedState.model === "test-slack-model" &&
      Array.isArray(adoptedState.thinking_logs) &&
      adoptedState.thinking_logs.length === 1,
    "adopted Slack row lost the normal assistant metadata"
  );
  logPass(
    "exact thread-sync winner is adopted without losing assistant metadata"
  );

  const conflictContent = "Expected Slack response";
  const conflictingAssistantId = await insertNormalSlackAssistant(sql, {
    content: conflictContent,
    jobId: IDS.conflictingReplyJob,
  });
  await insertNormalSlackAssistant(sql, {
    content: "Different Slack content",
    jobId: "thread-sync-conflict",
    slackMessageTs: "1700000031.000001",
    source: "slack_thread_sync",
  });
  await sql`
    insert into public.slack_reply_jobs(
      id, slack_event_id, thread_id, response_message_id, trigger_kind,
      slack_message_ts, prompt, status, locked_at, locked_by, response_text
    ) values (
      ${IDS.conflictingReplyJob}::uuid, 'Ev_CONFLICT', ${IDS.slackThread}::uuid,
      ${conflictingAssistantId}, 'mention', '1700000030.000001',
      'conflict prompt', 'processing', now(), 'db-test-worker', ${conflictContent}
    )
  `;
  await expectDbError(
    "Slack delivery content conflict",
    () =>
      finalizeSlackReply(sql, {
        jobId: IDS.conflictingReplyJob,
        slackMessageTs: "1700000031.000001",
      }),
    /Slack reply delivery conflict: existing Slack timestamp has different content or ownership/i
  );
  const conflictState = firstRow(
    await sql`
    select job.status, job.slack_response_ts,
           assistant.slack_message_ts as assistant_ts
    from public.slack_reply_jobs job
    join public.company_messages assistant on assistant.id = job.response_message_id
    where job.id = ${IDS.conflictingReplyJob}::uuid
  `
  );
  assert(
    conflictState.status === "processing" &&
      conflictState.slack_response_ts === null &&
      conflictState.assistant_ts === null,
    "delivery conflict partially completed the job or assistant"
  );
  logPass(
    "mismatched thread-sync delivery aborts with no partial finalization"
  );
}

async function testSlackProposalLifecycle(sql: Db) {
  await ensureSlackFixtures(sql);
  const userMessageId = await insertUserMessage(sql, {
    content: "회사 메모에 Slack 응답 방식을 저장해줘",
    messageType: "slack",
    slackMessageTs: "1700000001.000001",
    slackThreadId: IDS.slackThread,
    slackUserId: "U_TEST",
  });
  const changes = [
    {
      key: "workspace_memory",
      role_id: null,
      expected: null,
      value: "Slack에서는 먼저 결론을 설명한다.",
    },
  ];
  const presented = rpcResult(
    await sql`
    select public.present_company_agent_update_proposal_v1(
      ${IDS.workspaceA}::uuid,
      ${`slack:${IDS.slackThread}`},
      'slack',
      ${userMessageId},
      'Slack 응답 memory 수정',
      '+ Slack에서는 먼저 결론을 설명한다.',
      ${JSON.stringify({ changes, event_content: "DB Tester · Slack 응답 memory 수정" })}::jsonb,
      '회사 메모에 아래 내용을 저장할까요?\n\n+ Slack에서는 먼저 결론을 설명한다.',
      ${IDS.slackThread}::uuid,
      ${JSON.stringify({ llmUsage: { outputTokens: 20 }, toolResults: [{ name: "update_data" }] })}::jsonb,
      'test-slack-model',
      ${JSON.stringify([{ type: "summary", content: "slack thinking" }])}::jsonb,
      'slack'
    ) as result
  `
  );
  assert(
    presented.status === "draft",
    "Slack proposal was not staged as a draft"
  );
  const proposalId = String(presented.proposal_id);
  const beforeActivateCount = Number(
    value<number>(
      await sql`
    select count(*)::integer as count
    from public.company_messages
    where metadata #>> '{updateProposalRef,proposalId}' = ${proposalId}
  `,
      "count"
    )
  );
  assert(
    beforeActivateCount === 0,
    "Slack draft created an assistant message before delivery"
  );

  await sql`
    insert into public.slack_reply_jobs(
      slack_event_id, thread_id, user_message_id, response_proposal_id,
      trigger_kind, slack_message_ts, prompt, response_text
    ) values (
      'Ev_TEST', ${IDS.slackThread}::uuid, ${userMessageId}, ${proposalId}::uuid,
      'mention', '1700000001.000001', 'test prompt',
      '회사 메모에 아래 내용을 저장할까요?'
    )
  `;
  const activated = rpcResult(
    await sql`
    select public.activate_slack_company_agent_update_proposal_v1(
      ${proposalId}::uuid,
      '1700000002.000001',
      'U_BOT'
    ) as result
  `
  );
  assert(
    activated.status === "pending",
    "delivered Slack draft did not become pending"
  );
  const presentedMessageId = Number(activated.presented_message_id);
  const activatedMessage = firstRow(
    await sql`
    select message_type, model, metadata, thinking_logs, slack_message_ts
    from public.company_messages
    where id = ${presentedMessageId}
  `
  );
  const activatedMetadata = activatedMessage.metadata as Record<
    string,
    unknown
  >;
  assert(
    activatedMessage.message_type === "slack" &&
      activatedMessage.model === "test-slack-model",
    "Slack activation lost message fields"
  );
  assert(
    activatedMessage.slack_message_ts === "1700000002.000001",
    "Slack activation lost delivery timestamp"
  );
  assert(
    activatedMetadata.llmUsage !== undefined &&
      activatedMetadata.updateProposalRef !== undefined,
    "Slack activation lost durable metadata"
  );
  assert(
    Array.isArray(activatedMessage.thinking_logs) &&
      activatedMessage.thinking_logs.length === 1,
    "Slack activation lost thinking logs"
  );

  const retried = rpcResult(
    await sql`
    select public.activate_slack_company_agent_update_proposal_v1(
      ${proposalId}::uuid,
      '1700000002.000001',
      'U_BOT'
    ) as result
  `
  );
  assert(
    retried.status === "pending" &&
      Number(retried.presented_message_id) === presentedMessageId,
    "Slack activation retry was not idempotent"
  );
  const deliveredCount = Number(
    value<number>(
      await sql`
    select count(*)::integer as count
    from public.company_messages
    where slack_thread_id = ${IDS.slackThread}::uuid
      and slack_message_ts = '1700000002.000001'
  `,
      "count"
    )
  );
  assert(
    deliveredCount === 1,
    "Slack activation retry duplicated the assistant message"
  );
  logPass("Slack draft delivery is durable and activation is idempotent");

  const confirmMessageId = await insertUserMessage(sql, {
    content: "응",
    messageType: "slack",
    slackMessageTs: "1700000003.000001",
    slackThreadId: IDS.slackThread,
    slackUserId: "U_TEST",
  });
  const applied = await resolveProposal(sql, {
    action: "apply",
    currentUserMessageId: confirmMessageId,
    proposalId,
    scopeKey: `slack:${IDS.slackThread}`,
  });
  assert(
    applied.status === "applied",
    "adjacent Slack confirmation did not apply"
  );
  const memory = value<string>(
    await sql`
    select content from public.company_memories
    where company_workspace_id = ${IDS.workspaceA}::uuid and role_id is null
  `,
    "content"
  );
  assert(
    memory === "Slack에서는 먼저 결론을 설명한다.",
    "Slack proposal did not write exact workspace memory"
  );
  const jobProposal = value<string>(
    await sql`
    select response_proposal_id::text as response_proposal_id
    from public.slack_reply_jobs where slack_event_id = 'Ev_TEST'
  `,
    "response_proposal_id"
  );
  assert(
    jobProposal === proposalId,
    "Slack reply job lost its proposal reference"
  );
  logPass(
    "adjacent Slack confirmation applies exact memory and keeps job linkage"
  );
}

async function run() {
  const rawUrl = discoverDatabaseUrl();
  const sourceUrl = guardDatabaseUrl(rawUrl);
  const maintenance = postgres(maintenanceUrl(sourceUrl), {
    max: 1,
    connect_timeout: 10,
    idle_timeout: 5,
    onnotice: () => undefined,
  });
  const databaseName = `harper_org_agent_test_${process.pid}_${Date.now().toString(36)}`;
  const notices: string[] = [];
  let testDb: Db | null = null;
  let lockHolderDb: Db | null = null;
  let created = false;
  try {
    await ensureLocalRoles(maintenance);
    await maintenance.unsafe(`create database "${databaseName}"`);
    created = true;
    testDb = postgres(databaseUrl(sourceUrl, databaseName), {
      max: 1,
      connect_timeout: 10,
      idle_timeout: 5,
      onnotice: (notice) => notices.push(notice.message),
    });
    lockHolderDb = postgres(databaseUrl(sourceUrl, databaseName), {
      max: 1,
      connect_timeout: 10,
      idle_timeout: 5,
      onnotice: () => undefined,
    });

    await installBaseline(testDb);
    await testRequestMigration(testDb, notices);
    await applyRemainingMigrations(testDb);
    await testMemoryConstraints(testDb, lockHolderDb);
    await testRlsAndGrants(testDb);
    await testApplyRpcAndGuard(testDb, lockHolderDb);
    await testChatProposalLifecycle(testDb);
    await testSlackReplyFinalization(testDb);
    await testSlackProposalLifecycle(testDb);
    process.stdout.write(
      "ok - all company-side agent DB integration scenarios passed\n"
    );
  } catch (error) {
    const message =
      error instanceof Error ? error.stack || error.message : String(error);
    process.stderr.write(`${message}\n`);
    process.exitCode = 1;
  } finally {
    if (lockHolderDb) await lockHolderDb.end({ timeout: 5 });
    if (testDb) await testDb.end({ timeout: 5 });
    if (created) {
      try {
        await maintenance`
          select pg_terminate_backend(pid)
          from pg_stat_activity
          where datname = ${databaseName} and pid <> pg_backend_pid()
        `;
        await maintenance.unsafe(`drop database if exists "${databaseName}"`);
      } catch (cleanupError) {
        const message =
          cleanupError instanceof Error
            ? cleanupError.message
            : String(cleanupError);
        process.stderr.write(
          `[org-agent-db] failed to drop temporary database ${databaseName}: ${message}\n`
        );
        process.exitCode = 1;
      }
    }
    await maintenance.end({ timeout: 5 });
  }
}

void run().catch((error) => {
  const message =
    error instanceof Error ? error.stack || error.message : String(error);
  process.stderr.write(`${message}\n`);
  process.exitCode = 1;
});
