// Isolated PostgreSQL regression against read-only captured schema/functions.
// No production credentials, database connection, Slack, or LLM calls.
// Usage: PGLITE_MODULE_PATH=... node scripts/testCompanyFirstSearchSetting.mjs \
//   <schema-and-identities-v2.json> <live-functions.json>
import assert from "node:assert/strict";
import { randomUUID, createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { PGlite } = require(process.env.PGLITE_MODULE_PATH || "@electric-sql/pglite");
const [schemaPath, functionsPath] = process.argv.slice(2);
if (!schemaPath || !functionsPath) throw Error("Provide read-only captured schema and function JSON paths");
const schemaRaw = readFileSync(schemaPath, "utf8"), functionsRaw = readFileSync(functionsPath, "utf8");
const schema = JSON.parse(schemaRaw), functions = JSON.parse(functionsRaw);
const db = new PGlite();
const scalar = async (sql, args = []) => Object.values((await db.query(sql, args)).rows[0])[0];
const quote = (s) => '"' + s.replaceAll('"', '""') + '"';
const tables = ["company_db", "company_workspace", "company_data", "company_roles", "company_internal_roles", "company_memories", "company_events", "company_intro_candidates", "talent_users", "talent_setting", "company_user_workspace", "ops_matching_role_stages", "talent_conversations", "opportunity_discovery_run", "talent_opportunity_recommendation", "talent_opportunity_tag", "company_first_slack_outbox", "company_slack_channels", "company_slack_integrations", "company_role_notification_channels"];
try {
  await db.exec("create role anon; create role authenticated; create role service_role; set check_function_bodies=false;");
  for (const e of schema.enums) await db.exec(`create type public.${quote(e.name)} as enum (${e.labels.map(x => "'" + x.replaceAll("'", "''") + "'").join(",")})`);
  for (const s of schema.sequences) await db.exec(`create sequence public.${quote(s.sequence_name)}`);
  // Only schema is used from the private capture; identities/data are never loaded.
  for (const table of tables) {
    const cols = schema.columns.filter(c => c.table_name === table);
    assert.ok(cols.length, `Missing captured table ${table}`);
    const defs = cols.filter(c => !c.generated && !c.type.startsWith("vector")).map(c =>
      `${quote(c.name)} ${c.type} ${c.identity ? "generated by default as identity" : c.default_expr ? `default ${c.default_expr}` : ""}`);
    await db.exec(`create table public.${quote(table)} (${defs.join(",")})`);
  }
  // Exact keys needed by the real atomic mutation and lifecycle functions.
  await db.exec(`
    alter table company_workspace add primary key(company_workspace_id);
    alter table company_roles add primary key(role_id);
    alter table company_internal_roles add primary key(role_id);
    alter table company_intro_candidates add primary key(id);
    alter table talent_opportunity_recommendation add primary key(id);
    create unique index memory_role on company_memories(company_workspace_id,role_id) where role_id is not null;
    create unique index memory_workspace on company_memories(company_workspace_id) where role_id is null;
  `);
  const helper = schema.functions.find(f => f.name === "company_intro_role_allows_talent_v1");
  assert.ok(helper); await db.exec(helper.definition);
  for (const f of functions) {
    await db.exec(f.definition);
    await db.exec(`revoke all on function public.${f.proname}(${f.arguments}) from public,anon,authenticated; grant execute on function public.${f.proname}(${f.arguments}) to service_role;`);
  }
  await db.exec(`create trigger company_internal_role_close_company_intro_on_change
    after update of is_company_first_search on company_internal_roles
    for each row execute function close_company_intro_on_internal_role_change_v1();`);

  const workspace = randomUUID(), otherWorkspace = randomUUID(), user = randomUUID(), talent = randomUUID();
  const role = randomUUID(), otherRole = randomUUID(), externalRole = randomUUID(), missingRole = randomUUID();
  await db.query("insert into company_workspace(company_workspace_id,company_name) values ($1,'Synthetic Search Labs'),($2,'Other Synthetic Labs')", [workspace,otherWorkspace]);
  for (const [id,scope,source] of [[role,workspace,"internal"],[otherRole,otherWorkspace,"internal"],[externalRole,workspace,"external"],[missingRole,workspace,"internal"]]) {
    await db.query("insert into company_roles(role_id,company_workspace_id,name,source_type,status,is_expired,information) values ($1,$2,'Backend',$3,'active',false,$4)", [id,scope,source,JSON.stringify({ testOnly:true,testFixture:"company-first-search-setting-v1",testTalentIds:[talent] })]);
    if (id !== missingRole) await db.query("insert into company_internal_roles(role_id,is_company_first_search) values ($1,true)",[id]);
  }
  const addIntro = async (status = "ready") => scalar(`insert into company_intro_candidates
    (company_workspace_id,role_id,talent_id,status,selection_run_id,selection_reason,role_fingerprint,talent_fingerprint)
    values ($1,$2,$3,$4,$5,'Synthetic evidence','role-v1','talent-v1') returning id`,[workspace,role,talent,status,randomUUID()]);
  const intros = await Promise.all(["ready","awaiting_talent","connecting","connected","passed","closed"].map(s=>addIntro(s)));
  const rec = await scalar("insert into talent_opportunity_recommendation(role_id,talent_id,opportunity_type) values ($1,$2,'intro_request') returning id",[role,talent]);
  await db.query("update company_intro_candidates set recommendation_id=$1 where id=$2",[rec,intros[1]]);
  const artifacts = async () => (await db.query("select to_jsonb(i) as row from company_intro_candidates i order by id")).rows;
  const recommendations = async () => (await db.query("select to_jsonb(r) as row from talent_opportunity_recommendation r order by id")).rows;
  // Prove the captured baseline reproduces the bug, then roll it back.
  await db.exec("begin;");
  await db.query("update company_internal_roles set is_company_first_search=false where role_id=$1",[role]);
  assert.equal(await scalar("select status from company_intro_candidates where id=$1",[intros[0]]),"closed");
  await db.exec("rollback;");
  const before = await artifacts(), recBefore = await recommendations();
  const migration = readFileSync(new URL("../supabase/migrations/20260928024416_company_first_search_setting_without_intro_side_effects.sql",import.meta.url),"utf8");
  await db.exec(migration);
  const mutation = (value,expected=true,roleId=role) => ({key:"role_is_company_first_search",role_id:roleId,value,expected});
  const apply = (changes,source="chat") => scalar("select apply_company_data_changes_v1($1,$2::jsonb,$3,'Synthetic search setting change')",[workspace,JSON.stringify(changes),source]);
  const flag = () => scalar("select is_company_first_search from company_internal_roles where role_id=$1",[role]);
  assert.equal((await apply([mutation(false)],"slack")).status,"updated");
  assert.equal(await flag(),false);
  assert.deepEqual(await artifacts(),before,"turning off preserves every intro row byte-for-byte");
  assert.deepEqual(await recommendations(),recBefore,"turning off preserves candidate recommendations");
  assert.equal(await scalar("select status from company_roles where role_id=$1",[role]),"active");
  assert.equal(await scalar("select count(*)::int from opportunity_discovery_run"),0);
  assert.equal((await apply([mutation(false,false)])).status,"already_reflected");
  assert.equal(await scalar("select count(*)::int from company_events"),1);
  assert.equal((await apply([mutation(true,false)])).status,"updated");
  assert.equal(await flag(),true);
  // A stale flag prevents the entire mixed batch, including unrelated Role edits.
  assert.equal((await apply([{key:"role_name",role_id:role,value:"Changed",expected:"Backend"},mutation(false,false)])).status,"conflict");
  assert.equal(await scalar("select name from company_roles where role_id=$1",[role]),"Backend");
  for (const value of ["false",0,null,[],{}]) await assert.rejects(apply([mutation(value)]),/must be boolean/);
  await assert.rejects(apply([mutation(false,true,otherRole)]),/does not belong/);
  assert.equal((await apply([mutation(false,true,externalRole)])).status,"conflict");
  await assert.rejects(apply([mutation(false,null,externalRole)]),/active internal role/);
  await assert.rejects(apply([mutation(false,true,missingRole)]),/internal role settings not found/);
  await assert.rejects(apply([mutation(false),mutation(false)]),/duplicate/);
  await assert.rejects(apply([{...mutation(false),role_id:null}]),/role_id is required/);
  assert.equal(await flag(),true);
  assert.equal((await apply([{key:"role_name",role_id:role,value:"Updated Backend",expected:"Backend"},mutation(false)])).changed_count,2);
  assert.equal(await flag(),false);
  assert.equal(await scalar("select name from company_roles where role_id=$1",[role]),"Updated Backend");
  assert.deepEqual(await artifacts(),before);
  assert.deepEqual(await recommendations(),recBefore);
  await db.query("update company_internal_roles set is_company_first_search=true where role_id=$1",[role]);
  await db.query("update company_internal_roles set is_company_first_search=false where role_id=$1",[role]);
  assert.deepEqual(await artifacts(),before,"direct Ops writes preserve existing artifacts too");
  // Existing ready cards can still start an authorized intro; existing delivered
  // requests can still be accepted. These execute the real captured RPC bodies.
  await db.query("insert into company_user_workspace(company_user_id,company_workspace_id) values ($1,$2)",[user,workspace]);
  await db.query("insert into talent_users(user_id) values ($1)",[talent]);
  await db.query("insert into talent_setting(user_id,is_onboarding_done,profile_visibility,get_internal_recommendation) values ($1,true,'open_to_matches',true)",[talent]);
  const stage=await scalar("insert into ops_matching_role_stages(role_id,label) values ($1,'Interview') returning id",[role]);
  const request = id => scalar("select request_company_intro_v1($1,$2,$3,$4,array['fixture@example.invalid'],'Synthetic company interest')",[id,workspace,user,stage]);
  assert.equal((await request(intros[0])).status,"requested");
  assert.equal((await request(intros[0])).status,"already_requested");
  assert.equal(await scalar("select count(*)::int from opportunity_discovery_run"),1);
  assert.equal((await scalar("select decide_company_intro_request_v1($1,$2,'accept')",[talent,rec])).status,"accepted");
  assert.equal(await scalar("select status from company_intro_candidates where id=$1",[intros[1]]),"connecting");
  const blocked = await addIntro();
  await db.query("update talent_setting set profile_visibility='dont_share' where user_id=$1",[talent]);
  assert.equal((await request(blocked)).status,"talent_unavailable","privacy remains authoritative");
  await db.query("update talent_setting set profile_visibility='open_to_matches' where user_id=$1",[talent]);
  const ended = await addIntro();
  await db.query("update company_roles set status='ended' where role_id=$1",[role]);
  assert.equal((await request(ended)).status,"role_unavailable","ended Role remains unavailable");
  for (const name of ["request_company_intro_v1","decide_company_intro_request_v1","company_first_outbox_is_deliverable_v1"]) {
    assert.ok(!(await scalar("select prosrc from pg_proc where proname=$1",[name])).includes("is_company_first_search"));
    const privilege = await scalar("select bool_or(has_function_privilege('anon',oid,'execute') or has_function_privilege('authenticated',oid,'execute')) from pg_proc where proname=$1",[name]);
    assert.equal(privilege,false,"migration preserves service-only privileges");
  }
  assert.equal(await scalar("select count(*)::int from pg_trigger where tgname='company_internal_role_close_company_intro_on_change'"),0);
  const hash=x=>createHash('sha256').update(x).digest('hex');
  console.log(JSON.stringify({passed:true,checks:["captured bug reproduced","boolean true/false","chat/slack atomic mutation","same-value no-op","mixed-batch conflict","scope/type/missing-row rejection","Ops writes preserve all intro statuses and recommendations","request and accept with search disabled","privacy and Role closure guards","service-only privileges"],schemaHash:hash(schemaRaw),functionHash:hash(functionsRaw),migrationHash:hash(migration),limitations:"Isolated schema subset; no production writes or worker/Slack delivery. Fixture Roles always testOnly. Scheduled selection and outbox availability have separate guards."},null,2));
} finally { await db.close(); }
