-- VC portfolio company resolution and job-source cutover.
--
-- Deployment prerequisite:
--   Pause every workflow that can insert company_db rows, deploy the writer
--   changes that omit company_db.id for new rows, apply this migration, and
--   then resume those workflows.

begin;

lock table public.company_db in share row exclusive mode;

select setval(
  'public.organization_database_id_seq'::regclass,
  greatest(
    coalesce((select max(id) from public.company_db), 1),
    (select last_value from public.organization_database_id_seq)
  ),
  true
);

-- `company_db.id` is GENERATED BY DEFAULT AS IDENTITY in production. Identity
-- columns already use their owned sequence and PostgreSQL rejects SET DEFAULT
-- on them. Keep the fallback for older environments where the column is a
-- regular bigint backed by the same sequence.
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'company_db'
      and column_name = 'id'
      and is_identity = 'YES'
  ) then
    alter table public.company_db
      alter column id
      set default nextval('public.organization_database_id_seq'::regclass);
  end if;
end;
$$;

do $$
begin
  if exists (
    select 1
    from public.company_db
    where linkedin_company_id is not null
    group by linkedin_company_id
    having count(*) > 1
  ) then
    raise exception
      'cannot enforce LinkedIn company identity: duplicate linkedin_company_id values exist';
  end if;
end;
$$;

create unique index if not exists company_db_linkedin_company_id_uidx
  on public.company_db (linkedin_company_id)
  where linkedin_company_id is not null;

alter table public.jobs_companies_sources
  add column if not exists vc_canonical_company_id text,
  add column if not exists vc_company_name text;

create unique index if not exists jobs_companies_sources_vc_company_uidx
  on public.jobs_companies_sources (vc_canonical_company_id)
  where vc_canonical_company_id is not null;

create index if not exists jobs_companies_sources_vc_workspace_idx
  on public.jobs_companies_sources (company_workspace_id, vc_canonical_company_id)
  where vc_canonical_company_id is not null;

create or replace function public.preserve_vc_portfolio_source_metadata()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if coalesce(
    current_setting('harper.allow_vc_portfolio_metadata_write', true),
    ''
  ) <> 'on'
  and old.source_metadata ? 'vc_portfolio' then
    new.source_metadata := jsonb_set(
      coalesce(new.source_metadata, '{}'::jsonb),
      '{vc_portfolio}',
      old.source_metadata->'vc_portfolio',
      true
    );
  end if;
  return new;
end;
$$;

drop trigger if exists jobs_companies_sources_preserve_vc_portfolio
  on public.jobs_companies_sources;

create trigger jobs_companies_sources_preserve_vc_portfolio
before update of source_metadata on public.jobs_companies_sources
for each row
execute function public.preserve_vc_portfolio_source_metadata();

alter table public.jobposting_company_identity
  drop constraint if exists jobposting_company_identity_provider_check;

alter table public.jobposting_company_identity
  add constraint jobposting_company_identity_provider_check
  check (
    provider in (
      'wanted', 'linkedin', 'jobkorea', 'saramin',
      'greenhouse', 'lever', 'ashby', 'workday', 'other',
      'consider', 'getro'
    )
  );

do $$
begin
  if exists (
    select 1
    from public.jobposting_company_identity
    where provider in ('consider', 'getro')
    group by company_workspace_id
    having count(*) > 1
  ) then
    raise exception
      'cannot create VC workspace unique index: duplicate VC identities exist';
  end if;
end;
$$;

create unique index if not exists jobposting_company_identity_vc_workspace_uidx
  on public.jobposting_company_identity (company_workspace_id)
  where provider in ('consider', 'getro');

create or replace function public.vc_identity_is_operational(
  target_workspace_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.jobposting_company_identity identity_row
    where identity_row.company_workspace_id = target_workspace_id
      and identity_row.provider in ('consider', 'getro')
      and coalesce(
        (identity_row.evidence->'vc_jobs'->>'enabled')::boolean,
        false
      )
      and identity_row.evidence->'vc_jobs'->>'status' in (
        'primary',
        'switching',
        'degraded',
        'fallback_pending'
      )
  );
$$;

create or replace function public.lock_company_role_ingest(
  target_workspace_id uuid
)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
begin
  perform pg_advisory_xact_lock(
    hashtextextended(
      'company-role-ingest:' || target_workspace_id::text,
      0
    )
  );
end;
$$;

create or replace function public.guard_linkedin_role_write_for_vc_primary()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  fallback_workspace text;
begin
  if new.source_provider not in (
    'linkedin',
    'linkedin_jobs',
    'linkedin_jobs_scraping'
  ) then
    return new;
  end if;

  -- Participate in the same workspace serialization as VC transition apply.
  -- If LinkedIn gets the lock first, VC apply waits and its active-set
  -- fingerprint becomes stale. If VC gets it first, this trigger waits for
  -- commit and then observes the operational VC identity below.
  perform public.lock_company_role_ingest(new.company_workspace_id);

  fallback_workspace := current_setting(
    'harper.allow_linkedin_vc_fallback_workspace',
    true
  );
  if fallback_workspace = new.company_workspace_id::text then
    return new;
  end if;

  if public.vc_identity_is_operational(new.company_workspace_id) then
    -- Returning NULL from a BEFORE trigger skips the row. This is the final
    -- write-time guard for LinkedIn jobs that passed their target gate before
    -- a VC cutover committed.
    return null;
  end if;

  return new;
end;
$$;

drop trigger if exists company_roles_guard_linkedin_vc_primary
  on public.company_roles;

create trigger company_roles_guard_linkedin_vc_primary
before insert or update on public.company_roles
for each row
execute function public.guard_linkedin_role_write_for_vc_primary();

revoke all on function public.vc_identity_is_operational(uuid) from public;
revoke all on function public.lock_company_role_ingest(uuid) from public;
grant execute on function public.vc_identity_is_operational(uuid) to service_role;
grant execute on function public.lock_company_role_ingest(uuid) to service_role;

commit;
