alter table if exists public.talent_users
  add column if not exists name text,
  add column if not exists profile_picture text,
  add column if not exists headline text,
  add column if not exists bio text,
  add column if not exists location text;

create table if not exists public.talent_experiences (
  id bigint generated by default as identity primary key,
  talent_id uuid not null
    references public.talent_users (user_id)
    on delete cascade,
  role text,
  description text,
  start_date date,
  end_date date,
  months integer,
  company_name text,
  company_location text,
  memo text,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists talent_experiences_talent_id_idx
  on public.talent_experiences (talent_id);

create table if not exists public.talent_educations (
  id bigint generated by default as identity primary key,
  talent_id uuid not null
    references public.talent_users (user_id)
    on delete cascade,
  school text,
  degree text,
  field text,
  start_date date,
  end_date date,
  url text,
  memo text,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists talent_educations_talent_id_idx
  on public.talent_educations (talent_id);

create table if not exists public.talent_publications (
  id bigint generated by default as identity primary key,
  talent_id uuid not null
    references public.talent_users (user_id)
    on delete cascade,
  title text,
  abstract text,
  citation_num integer,
  published_at text,
  link text,
  memo text,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists talent_publications_talent_id_idx
  on public.talent_publications (talent_id);

create table if not exists public.talent_extras (
  talent_id uuid primary key
    references public.talent_users (user_id)
    on delete cascade,
  content jsonb not null default '{}'::jsonb
);

alter table public.talent_experiences enable row level security;
alter table public.talent_educations enable row level security;
alter table public.talent_publications enable row level security;
alter table public.talent_extras enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'talent_experiences'
      and policyname = 'Users can manage own talent_experiences'
  ) then
    create policy "Users can manage own talent_experiences"
      on public.talent_experiences
      for all
      using (auth.uid() = talent_id)
      with check (auth.uid() = talent_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'talent_educations'
      and policyname = 'Users can manage own talent_educations'
  ) then
    create policy "Users can manage own talent_educations"
      on public.talent_educations
      for all
      using (auth.uid() = talent_id)
      with check (auth.uid() = talent_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'talent_publications'
      and policyname = 'Users can manage own talent_publications'
  ) then
    create policy "Users can manage own talent_publications"
      on public.talent_publications
      for all
      using (auth.uid() = talent_id)
      with check (auth.uid() = talent_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'talent_extras'
      and policyname = 'Users can manage own talent_extras'
  ) then
    create policy "Users can manage own talent_extras"
      on public.talent_extras
      for all
      using (auth.uid() = talent_id)
      with check (auth.uid() = talent_id);
  end if;
end
$$;
