create table if not exists public.talent_internal (
  id bigint generated by default as identity primary key,
  talent_id uuid not null,
  waitlist_id bigint not null,
  type text not null,
  content text not null,
  from_email text null,
  to_email text null,
  subject text null,
  created_by text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists talent_internal_waitlist_created_idx
  on public.talent_internal (waitlist_id, created_at desc);

create index if not exists talent_internal_talent_created_idx
  on public.talent_internal (talent_id, created_at desc);

do $$
begin
  alter table public.talent_internal
    add constraint talent_internal_type_check
    check (type in ('mail', 'memo', 'conversation'));
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  alter table public.talent_internal
    add constraint talent_internal_talent_id_fkey
    foreign key (talent_id) references public.talent_users(user_id)
    on delete cascade;
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  alter table public.talent_internal
    add constraint talent_internal_waitlist_id_fkey
    foreign key (waitlist_id) references public.harper_waitlist(id)
    on delete cascade;
exception
  when duplicate_object then null;
end
$$;
