create extension if not exists vector;

create table if not exists public.talent_contexts (
  id bigint generated by default as identity primary key,
  talent_id uuid not null references public.talent_users(user_id) on delete cascade,
  ref bigint not null,
  collection text not null,
  label text,
  key text,
  content text not null,
  source_refs jsonb not null default '[]'::jsonb,
  revision bigint not null default 1,
  embedding vector(1536),
  embedding_model text,
  embedding_content_hash text,
  embedding_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint talent_contexts_collection_check
    check (collection in ('brief', 'memory')),
  constraint talent_contexts_content_check
    check (length(btrim(content)) between 1 and 8000),
  constraint talent_contexts_label_check
    check (
      (collection = 'brief' and label is not null and length(btrim(label)) between 1 and 160)
      or (collection = 'memory' and label is null)
    ),
  constraint talent_contexts_key_check
    check (key is null or (collection = 'brief' and length(btrim(key)) between 1 and 160)),
  constraint talent_contexts_source_refs_check
    check (jsonb_typeof(source_refs) = 'array')
);

create unique index if not exists talent_contexts_active_key_uidx
  on public.talent_contexts (talent_id, key)
  where collection = 'brief' and key is not null and deleted_at is null;

create unique index if not exists talent_contexts_talent_ref_uidx
  on public.talent_contexts (talent_id, ref);

create index if not exists talent_contexts_active_collection_idx
  on public.talent_contexts (talent_id, collection, updated_at desc, id desc)
  where deleted_at is null;

create index if not exists talent_contexts_pending_embedding_idx
  on public.talent_contexts (updated_at, id)
  where collection = 'memory' and deleted_at is null and embedding is null;

alter table public.talent_contexts enable row level security;

revoke insert, update, delete on table public.talent_contexts
  from anon, authenticated;
grant select on table public.talent_contexts to authenticated;
grant all on table public.talent_contexts to service_role;
grant usage, select on sequence public.talent_contexts_id_seq to service_role;

drop policy if exists talent_contexts_insert_own on public.talent_contexts;
drop policy if exists talent_contexts_update_own on public.talent_contexts;
drop policy if exists talent_contexts_delete_own on public.talent_contexts;

drop policy if exists talent_contexts_select_own on public.talent_contexts;
create policy talent_contexts_select_own
  on public.talent_contexts
  for select
  to authenticated
  using (auth.uid() = talent_id);

create table if not exists public.talent_context_write_requests (
  talent_id uuid not null references public.talent_users(user_id) on delete cascade,
  request_id text not null,
  response jsonb,
  created_at timestamptz not null default now(),
  primary key (talent_id, request_id),
  constraint talent_context_write_requests_request_id_check
    check (length(btrim(request_id)) between 1 and 240)
);

alter table public.talent_context_write_requests enable row level security;

create index if not exists talent_context_write_requests_retention_idx
  on public.talent_context_write_requests (talent_id, created_at);

revoke all on table public.talent_context_write_requests
  from public, anon, authenticated;
grant all on table public.talent_context_write_requests to service_role;

create or replace function public.mutate_talent_contexts(
  p_talent_id uuid,
  p_request_id text,
  p_changes jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_existing_response jsonb;
  v_claimed integer;
  v_change jsonb;
  v_index integer;
  v_op text;
  v_collection text;
  v_label text;
  v_key text;
  v_content text;
  v_source_refs jsonb;
  v_id bigint;
  v_ref bigint;
  v_expected_revision bigint;
  v_row public.talent_contexts%rowtype;
  v_applied jsonb := '[]'::jsonb;
begin
  if p_talent_id is null then
    raise exception 'talent_id is required' using errcode = '22023';
  end if;
  if p_request_id is null or length(btrim(p_request_id)) = 0 then
    raise exception 'request_id is required' using errcode = '22023';
  end if;
  if p_changes is null
    or jsonb_typeof(p_changes) <> 'array'
    or jsonb_array_length(p_changes) = 0
  then
    raise exception 'changes must be a non-empty array' using errcode = '22023';
  end if;
  if jsonb_array_length(p_changes) > 20 then
    raise exception 'changes exceeds the maximum of 20' using errcode = '22023';
  end if;

  -- A request cannot be retried through the product after this window. Keep
  -- the idempotency ledger bounded instead of accumulating one row forever.
  delete from public.talent_context_write_requests
  where talent_id = p_talent_id
    and created_at < now() - interval '30 days';

  select response
  into v_existing_response
  from public.talent_context_write_requests
  where talent_id = p_talent_id and request_id = btrim(p_request_id);

  if found and v_existing_response is not null then
    return v_existing_response;
  end if;

  insert into public.talent_context_write_requests (talent_id, request_id)
  values (p_talent_id, btrim(p_request_id))
  on conflict do nothing;
  get diagnostics v_claimed = row_count;

  if v_claimed = 0 then
    select response
    into v_existing_response
    from public.talent_context_write_requests
    where talent_id = p_talent_id and request_id = btrim(p_request_id)
    for update;
    if v_existing_response is not null then
      return v_existing_response;
    end if;
  end if;

  for v_change, v_index in
    select value, ordinality::integer
    from jsonb_array_elements(p_changes) with ordinality
  loop
    v_op := lower(btrim(coalesce(v_change ->> 'op', '')));

    if v_op = 'add' then
      v_collection := lower(btrim(coalesce(v_change ->> 'collection', '')));
      v_label := nullif(btrim(coalesce(v_change ->> 'label', '')), '');
      v_key := nullif(btrim(coalesce(v_change ->> 'key', '')), '');
      v_content := btrim(coalesce(v_change ->> 'content', ''));
      v_source_refs := coalesce(v_change -> 'source_refs', '[]'::jsonb);

      if v_collection not in ('brief', 'memory') then
        raise exception 'invalid collection at change %', v_index using errcode = '22023';
      end if;
      if length(v_content) = 0 or length(v_content) > 8000 then
        raise exception 'invalid content at change %', v_index using errcode = '22023';
      end if;
      if v_collection = 'brief' and (v_label is null or length(v_label) > 160) then
        raise exception 'brief label is required at change %', v_index using errcode = '22023';
      end if;
      if v_collection = 'memory' then
        v_label := null;
        v_key := null;
      end if;
      if jsonb_typeof(v_source_refs) <> 'array' then
        raise exception 'source_refs must be an array at change %', v_index using errcode = '22023';
      end if;

      if v_key is not null then
        select *
        into v_row
        from public.talent_contexts
        where talent_id = p_talent_id
          and collection = 'brief'
          and key = v_key
          and deleted_at is null
        for update;
      else
        v_row := null;
      end if;

      if v_row.id is null then
        perform pg_advisory_xact_lock(hashtextextended(p_talent_id::text, 0));
        if v_key is not null then
          select *
          into v_row
          from public.talent_contexts
          where talent_id = p_talent_id
            and collection = 'brief'
            and key = v_key
            and deleted_at is null
          for update;
        end if;
      end if;

      if v_row.id is null then
        select coalesce(max(ref), 0) + 1
        into v_ref
        from public.talent_contexts
        where talent_id = p_talent_id;
        insert into public.talent_contexts (
          talent_id, ref, collection, label, key, content, source_refs
        ) values (
          p_talent_id, v_ref, v_collection, v_label, v_key, v_content, v_source_refs
        )
        returning * into v_row;
      elsif v_key is not null then
        update public.talent_contexts
        set
          label = v_label,
          content = v_content,
          source_refs = source_refs || v_source_refs,
          revision = revision + 1,
          updated_at = now(),
          embedding = null,
          embedding_model = null,
          embedding_content_hash = null,
          embedding_updated_at = null
        where id = v_row.id
          and talent_id = p_talent_id
          and deleted_at is null
        returning * into v_row;
      end if;

    elsif v_op = 'update' then
      v_id := nullif(v_change ->> 'id', '')::bigint;
      v_expected_revision := nullif(v_change ->> 'expected_revision', '')::bigint;
      if v_id is null or v_expected_revision is null then
        raise exception 'id and expected_revision are required at change %', v_index using errcode = '22023';
      end if;
      if not (v_change ? 'content') and not (v_change ? 'label') then
        raise exception 'update content or label is required at change %', v_index using errcode = '22023';
      end if;
      if v_change ? 'source_refs'
        and jsonb_typeof(v_change -> 'source_refs') <> 'array'
      then
        raise exception 'source_refs must be an array at change %', v_index using errcode = '22023';
      end if;

      update public.talent_contexts
      set
        label = case
          when v_change ? 'label' and collection = 'brief'
            then nullif(btrim(coalesce(v_change ->> 'label', '')), '')
          else label
        end,
        content = case
          when v_change ? 'content' then btrim(coalesce(v_change ->> 'content', ''))
          else content
        end,
        source_refs = case
          when v_change ? 'source_refs' then source_refs || (v_change -> 'source_refs')
          else source_refs
        end,
        revision = revision + 1,
        updated_at = now(),
        embedding = case when v_change ? 'content' then null else embedding end,
        embedding_model = case when v_change ? 'content' then null else embedding_model end,
        embedding_content_hash = case when v_change ? 'content' then null else embedding_content_hash end,
        embedding_updated_at = case when v_change ? 'content' then null else embedding_updated_at end
      where id = v_id
        and talent_id = p_talent_id
        and deleted_at is null
        and revision = v_expected_revision
        and (not (v_change ? 'label') or collection = 'brief')
      returning * into v_row;

      if v_row.id is null then
        raise exception 'talent context conflict at change %', v_index using errcode = '40001';
      end if;

    elsif v_op = 'delete' then
      v_id := nullif(v_change ->> 'id', '')::bigint;
      v_expected_revision := nullif(v_change ->> 'expected_revision', '')::bigint;
      if v_id is null or v_expected_revision is null then
        raise exception 'id and expected_revision are required at change %', v_index using errcode = '22023';
      end if;

      update public.talent_contexts
      set deleted_at = now(), revision = revision + 1, updated_at = now()
      where id = v_id
        and talent_id = p_talent_id
        and deleted_at is null
        and revision = v_expected_revision
      returning * into v_row;

      if v_row.id is null then
        raise exception 'talent context conflict at change %', v_index using errcode = '40001';
      end if;
    else
      raise exception 'invalid operation at change %', v_index using errcode = '22023';
    end if;

    v_applied := v_applied || jsonb_build_array(jsonb_build_object(
      'change_index', v_index - 1,
      'op', v_op,
      'id', v_row.id,
      'ref', v_row.ref,
      'talent_id', v_row.talent_id,
      'collection', v_row.collection,
      'label', v_row.label,
      'key', v_row.key,
      'content', v_row.content,
      'source_refs', v_row.source_refs,
      'revision', v_row.revision,
      'created_at', v_row.created_at,
      'updated_at', v_row.updated_at,
      'deleted_at', v_row.deleted_at
    ));
    v_row := null;
  end loop;

  v_existing_response := jsonb_build_object('applied', v_applied);
  update public.talent_context_write_requests
  set response = v_existing_response
  where talent_id = p_talent_id and request_id = btrim(p_request_id);

  return v_existing_response;
end;
$$;

revoke all on function public.mutate_talent_contexts(uuid, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.mutate_talent_contexts(uuid, text, jsonb)
  to service_role;

create or replace function public.match_talent_context_memories(
  p_talent_id uuid,
  p_query_embedding vector(1536),
  p_match_count integer default 12,
  p_embedding_model text default 'text-embedding-3-small'
)
returns table (
  id bigint,
  ref bigint,
  talent_id uuid,
  collection text,
  label text,
  key text,
  content text,
  source_refs jsonb,
  revision bigint,
  created_at timestamptz,
  updated_at timestamptz,
  score double precision
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select
    c.id,
    c.ref,
    c.talent_id,
    c.collection,
    c.label,
    c.key,
    c.content,
    c.source_refs,
    c.revision,
    c.created_at,
    c.updated_at,
    1 - (c.embedding <=> p_query_embedding) as score
  from public.talent_contexts c
  where c.talent_id = p_talent_id
    and c.collection = 'memory'
    and c.deleted_at is null
    and c.embedding is not null
    and c.embedding_model = p_embedding_model
  order by c.embedding <=> p_query_embedding, c.updated_at desc
  limit greatest(1, least(p_match_count, 40));
$$;

revoke all on function public.match_talent_context_memories(uuid, vector, integer, text)
  from public, anon, authenticated;
grant execute on function public.match_talent_context_memories(uuid, vector, integer, text)
  to service_role;

insert into public.talent_contexts (
  talent_id,
  ref,
  collection,
  label,
  key,
  content,
  source_refs,
  created_at,
  updated_at
)
select
  insight.talent_id,
  row_number() over (partition by insight.talent_id order by insight.id, entry.key),
  'brief',
  case entry.key
    when 'search_intensity' then '이직 적극도'
    when 'location' then '선호 근무 지역'
    when 'next_scope' then '다음 역할'
    when 'must_haves' then '꼭 있어야 하는 조건'
    when 'compensation' then '기대 보상 조건'
    when 'cross_border_work_authorization' then '거주국 외 국가의 근무 자격'
    when 'language' then '외국어 능력'
    when 'deal_breakers' then '피하고 싶은 조건'
    when 'team_style_fit' then '선호하는 회사의 조건'
    else initcap(replace(entry.key, '_', ' '))
  end,
  entry.key,
  btrim(entry.value),
  jsonb_build_array(jsonb_build_object(
    'type', 'talent_insights_migration',
    'insight_id', insight.id
  )),
  coalesce(insight.created_at, now()),
  coalesce(insight.last_updated_at, insight.created_at, now())
from public.talent_insights insight
cross join lateral jsonb_each_text(coalesce(insight.content, '{}'::jsonb)) entry
where insight.talent_id is not null
  and length(btrim(entry.value)) > 0
on conflict (talent_id, key)
  where collection = 'brief' and key is not null and deleted_at is null
do nothing;

-- Preserve the existing Behavior Context as Memory during the one-time cutover.
-- It is already an LLM-authored heading-and-bullet document, so each existing
-- bullet becomes one readable Memory row without another model call.
with behavior_lines as (
  select
    behavior.talent_id,
    line.ordinality,
    btrim(line.value) as value,
    behavior.context_version,
    behavior.created_at,
    behavior.updated_at
  from public.talent_behavior_contexts behavior
  cross join lateral regexp_split_to_table(
    replace(behavior.context_text, E'\r', ''),
    E'\n'
  ) with ordinality as line(value, ordinality)
  where length(btrim(behavior.context_text)) > 0
), annotated_lines as (
  select
    *,
    max(case when value not like '- %' then ordinality end) over (
      partition by talent_id
      order by ordinality
      rows between unbounded preceding and current row
    ) as heading_ordinality
  from behavior_lines
  where length(value) > 0
), behavior_memories as (
  select
    fact.talent_id,
    row_number() over (
      partition by fact.talent_id
      order by fact.ordinality
    ) as memory_number,
    concat(heading.value, ': ', substring(fact.value from 3)) as content,
    fact.context_version,
    fact.ordinality as source_line,
    fact.created_at,
    fact.updated_at
  from annotated_lines fact
  join behavior_lines heading
    on heading.talent_id = fact.talent_id
   and heading.ordinality = fact.heading_ordinality
  where fact.value like '- %'
), behavior_fallback_memories as (
  select
    behavior.talent_id,
    1::bigint as memory_number,
    btrim(behavior.context_text) as content,
    behavior.context_version,
    null::bigint as source_line,
    behavior.created_at,
    behavior.updated_at
  from public.talent_behavior_contexts behavior
  where length(btrim(behavior.context_text)) > 0
    and not exists (
      select 1
      from behavior_memories memory
      where memory.talent_id = behavior.talent_id
    )
), all_behavior_memories as (
  select * from behavior_memories
  union all
  select * from behavior_fallback_memories
), existing_refs as (
  select talent_id, coalesce(max(ref), 0) as max_ref
  from public.talent_contexts
  group by talent_id
)
insert into public.talent_contexts (
  talent_id,
  ref,
  collection,
  content,
  source_refs,
  created_at,
  updated_at
)
select
  memory.talent_id,
  coalesce(existing.max_ref, 0) + memory.memory_number,
  'memory',
  memory.content,
  jsonb_build_array(jsonb_build_object(
    'type', 'talent_behavior_context_migration',
    'context_version', memory.context_version,
    'source_line', memory.source_line
  )),
  memory.created_at,
  memory.updated_at
from all_behavior_memories memory
left join existing_refs existing on existing.talent_id = memory.talent_id
where length(memory.content) between 1 and 8000;
