begin;

-- Activity payloads are generated by several independent producers. Keep the
-- value descriptive instead of rejecting an otherwise valid event.
alter table public.talent_activity_events
  drop constraint if exists talent_activity_events_impact_level_check;

alter table public.talent_documents
  add column if not exists content_sha256 text;

create index if not exists talent_documents_content_sha256_idx
  on public.talent_documents (talent_id, kind, content_sha256)
  where content_sha256 is not null;

create or replace function public.finalize_talent_onboarding_submission_v1(
  p_user_id uuid,
  p_conversation_id uuid,
  p_profile_submit_content text,
  p_kickoff_content text,
  p_pending_question_content text,
  p_is_mobile boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_conversation public.talent_conversations%rowtype;
  v_user_message public.talent_messages%rowtype;
  v_kickoff_message public.talent_messages%rowtype;
  v_pending_message public.talent_messages%rowtype;
  v_inserted boolean := false;
begin
  select * into v_conversation
  from public.talent_conversations
  where id = p_conversation_id
    and user_id = p_user_id
  for update;

  if not found then
    raise exception using
      errcode = 'P0002',
      message = 'talent_conversation_not_found';
  end if;

  select * into v_user_message
  from public.talent_messages
  where conversation_id = p_conversation_id
    and user_id = p_user_id
    and message_type = 'profile_submit'
  order by id asc
  limit 1;

  if v_user_message.id is null then
    insert into public.talent_messages (
      conversation_id,
      user_id,
      role,
      content,
      message_type,
      is_mobile
    ) values (
      p_conversation_id,
      p_user_id,
      'user',
      p_profile_submit_content,
      'profile_submit',
      p_is_mobile
    ) returning * into v_user_message;

    insert into public.talent_messages (
      conversation_id,
      user_id,
      role,
      content,
      message_type,
      is_mobile
    ) values (
      p_conversation_id,
      p_user_id,
      'assistant',
      p_kickoff_content,
      'system',
      p_is_mobile
    ) returning * into v_kickoff_message;

    insert into public.talent_messages (
      conversation_id,
      user_id,
      role,
      content,
      message_type,
      is_mobile
    ) values (
      p_conversation_id,
      p_user_id,
      'assistant',
      p_pending_question_content,
      'system',
      p_is_mobile
    ) returning * into v_pending_message;

    v_inserted := true;
  else
    select * into v_kickoff_message
    from public.talent_messages
    where conversation_id = p_conversation_id
      and user_id = p_user_id
      and role = 'assistant'
      and message_type = 'system'
      and id > v_user_message.id
    order by id asc
    limit 1;

    select * into v_pending_message
    from public.talent_messages
    where conversation_id = p_conversation_id
      and user_id = p_user_id
      and role = 'assistant'
      and message_type = 'system'
      and id > coalesce(v_kickoff_message.id, v_user_message.id)
    order by id asc
    limit 1;
  end if;

  update public.talent_conversations
  set stage = 'chat', updated_at = now()
  where id = p_conversation_id
    and user_id = p_user_id
  returning * into v_conversation;

  return jsonb_build_object(
    'inserted', v_inserted,
    'conversation', to_jsonb(v_conversation),
    'userMessage', to_jsonb(v_user_message),
    'assistantMessages', jsonb_build_array(
      to_jsonb(v_kickoff_message),
      to_jsonb(v_pending_message)
    )
  );
end;
$$;

create or replace function public.upsert_talent_document_by_hash_v1(
  p_talent_id uuid,
  p_kind text,
  p_file_name text,
  p_storage_path text,
  p_content_type text,
  p_size_bytes bigint,
  p_content_sha256 text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_document public.talent_documents%rowtype;
  v_created boolean := false;
begin
  perform 1
  from public.talent_users
  where user_id = p_talent_id
  for update;

  if not found then
    raise exception using
      errcode = 'P0002',
      message = 'talent_user_not_found';
  end if;

  select * into v_document
  from public.talent_documents
  where talent_id = p_talent_id
    and kind = p_kind
    and content_sha256 = p_content_sha256
  order by created_at desc
  limit 1;

  if p_kind = 'resume' then
    update public.talent_documents
    set is_primary = false, is_public = false
    where talent_id = p_talent_id
      and kind = 'resume'
      and is_primary = true
      and (v_document.id is null or id <> v_document.id);
  end if;

  if v_document.id is null then
    insert into public.talent_documents (
      talent_id,
      kind,
      file_name,
      storage_path,
      content_type,
      size_bytes,
      content_sha256,
      is_public,
      is_primary
    ) values (
      p_talent_id,
      p_kind,
      p_file_name,
      p_storage_path,
      p_content_type,
      p_size_bytes,
      p_content_sha256,
      p_kind = 'resume',
      p_kind = 'resume'
    ) returning * into v_document;
    v_created := true;
  elsif p_kind = 'resume' then
    update public.talent_documents
    set is_primary = true, is_public = true
    where id = v_document.id
    returning * into v_document;
  end if;

  if p_kind = 'resume' then
    update public.talent_users
    set
      resume_file_name = v_document.file_name,
      resume_storage_path = v_document.storage_path,
      resume_text = v_document.extracted_text,
      updated_at = now()
    where user_id = p_talent_id;
  end if;

  return jsonb_build_object(
    'created', v_created,
    'document', to_jsonb(v_document)
  );
end;
$$;

revoke all on function public.finalize_talent_onboarding_submission_v1(
  uuid, uuid, text, text, text, boolean
) from public, anon, authenticated;
grant execute on function public.finalize_talent_onboarding_submission_v1(
  uuid, uuid, text, text, text, boolean
) to service_role;

revoke all on function public.upsert_talent_document_by_hash_v1(
  uuid, text, text, text, text, bigint, text
) from public, anon, authenticated;
grant execute on function public.upsert_talent_document_by_hash_v1(
  uuid, text, text, text, text, bigint, text
) to service_role;

comment on column public.talent_documents.content_sha256 is
  'SHA-256 content digest used to make repeated uploads idempotent per talent and document kind.';

commit;
