insert into public.official_jobs (
  slug,
  company_name,
  role_title,
  location,
  vertical,
  short_description,
  company_description_markdown,
  role_description_markdown,
  compensation,
  employment_type,
  seniority,
  display_order,
  is_published,
  published_at
) values (
  'internal-internal',
  'Harper',
  'internal_internal',
  'Internal',
  'Internal',
  'Internal copy source for official jobs landing pages.',
  '',
  '',
  null,
  null,
  null,
  -1000,
  false,
  null
)
on conflict (slug) do update set
  company_name = excluded.company_name,
  role_title = excluded.role_title,
  location = excluded.location,
  vertical = excluded.vertical,
  short_description = excluded.short_description,
  compensation = excluded.compensation,
  employment_type = excluded.employment_type,
  seniority = excluded.seniority,
  display_order = excluded.display_order,
  is_published = false,
  published_at = null,
  updated_at = timezone('utc', now());
