create table if not exists public.llm_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  source text not null,
  model text not null,
  estimated_cost_usd numeric(12, 8) not null default 0,
  meta jsonb not null default '{}'::jsonb
);

alter table public.llm_logs
  drop column if exists input_tokens,
  drop column if exists output_tokens,
  drop column if exists total_tokens,
  drop column if exists latency_ms;

create index if not exists llm_logs_source_created_at_idx
  on public.llm_logs (source, created_at desc);

alter table public.llm_logs enable row level security;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant select, insert on public.llm_logs to service_role';
  end if;

  if exists (select 1 from pg_roles where rolname = 'harper_worker') then
    execute 'grant select, insert on public.llm_logs to harper_worker';

    execute 'drop policy if exists llm_logs_harper_worker_all on public.llm_logs';
    execute 'create policy llm_logs_harper_worker_all
      on public.llm_logs
      for all
      to harper_worker
      using (true)
      with check (true)';
  end if;
end;
$$;
