alter table public.payments
  add column if not exists provider text,
  add column if not exists provider_status text,
  add column if not exists toss_customer_key text,
  add column if not exists toss_billing_key text,
  add column if not exists toss_last_payment_key text,
  add column if not exists toss_last_order_id text,
  add column if not exists next_charge_at timestamptz,
  add column if not exists retry_next_at timestamptz,
  add column if not exists retry_count integer,
  add column if not exists grace_ends_at timestamptz,
  add column if not exists cancelled_at timestamptz,
  add column if not exists card_company text,
  add column if not exists card_number_masked text;

create table if not exists public.billing_sessions (
  id bigint generated by default as identity primary key,
  session_token text not null unique,
  user_id uuid not null references public.company_users(user_id) on delete cascade,
  payment_id bigint references public.payments(id) on delete set null,
  plan_id uuid not null references public.plans(plan_id) on delete restrict,
  plan_key text not null,
  billing text not null,
  amount_krw integer not null,
  reason text not null,
  status text not null default 'pending',
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz default now()
);

create table if not exists public.payment_attempts (
  id bigint generated by default as identity primary key,
  payment_id bigint references public.payments(id) on delete set null,
  user_id uuid not null references public.company_users(user_id) on delete cascade,
  provider text not null,
  attempt_key text not null unique,
  reason text not null,
  plan_id uuid references public.plans(plan_id) on delete set null,
  amount_krw integer not null,
  order_id text not null unique,
  status text not null,
  payment_key text,
  approved_at timestamptz,
  failure_code text,
  failure_message text,
  receipt_url text,
  raw_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz default now()
);

create index if not exists payments_user_provider_idx
  on public.payments (user_id, provider);

create index if not exists payments_provider_status_idx
  on public.payments (provider, provider_status);

create index if not exists payments_next_charge_at_idx
  on public.payments (next_charge_at);

create index if not exists payments_retry_next_at_idx
  on public.payments (retry_next_at);

create index if not exists payments_grace_ends_at_idx
  on public.payments (grace_ends_at);

create index if not exists billing_sessions_user_status_idx
  on public.billing_sessions (user_id, status);

create index if not exists billing_sessions_expires_at_idx
  on public.billing_sessions (expires_at);

create index if not exists payment_attempts_user_created_idx
  on public.payment_attempts (user_id, created_at desc);

create index if not exists payment_attempts_payment_created_idx
  on public.payment_attempts (payment_id, created_at desc);
