create table if not exists public.candidate_outreach_workspace (
  user_id uuid primary key references public.company_users(user_id) on delete cascade,
  job_description text null,
  sender_email text null,
  company_pitch text null,
  signature text null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.candidate_outreach (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.company_users(user_id) on delete cascade,
  candid_id uuid not null references public.candid(id) on delete cascade,
  target_email text null,
  email_source_type text null,
  email_source_label text null,
  email_source_url text null,
  email_discovery_status text not null default 'not_started',
  email_discovery_summary text null,
  email_discovery_trace jsonb not null default '[]'::jsonb,
  email_discovery_evidence jsonb not null default '[]'::jsonb,
  sequence_status text not null default 'draft',
  active_step integer not null default 0,
  last_sent_at timestamptz null,
  next_due_at timestamptz null,
  stopped_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint candidate_outreach_user_candid_unique unique (user_id, candid_id)
);

create table if not exists public.candidate_outreach_message (
  id bigint generated by default as identity primary key,
  outreach_id bigint null references public.candidate_outreach(id) on delete cascade,
  user_id uuid not null references public.company_users(user_id) on delete cascade,
  candid_id uuid not null references public.candid(id) on delete cascade,
  kind text not null,
  step_number integer null,
  status text not null default 'draft',
  subject text not null,
  body text not null,
  rendered_subject text null,
  rendered_body text null,
  to_email text null,
  sent_at timestamptz null,
  created_by text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists candidate_outreach_user_updated_idx
  on public.candidate_outreach (user_id, updated_at desc);

create index if not exists candidate_outreach_user_sequence_idx
  on public.candidate_outreach (user_id, sequence_status, next_due_at desc nulls last);

create index if not exists candidate_outreach_message_user_created_idx
  on public.candidate_outreach_message (user_id, created_at desc);

create unique index if not exists candidate_outreach_message_sequence_unique
  on public.candidate_outreach_message (user_id, candid_id, step_number)
  where kind = 'sequence' and step_number is not null;

do $$
begin
  alter table public.candidate_outreach
    add constraint candidate_outreach_email_source_type_check
    check (
      email_source_type is null
      or email_source_type in ('candid', 'github', 'scholar', 'web', 'manual')
    );
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  alter table public.candidate_outreach
    add constraint candidate_outreach_email_discovery_status_check
    check (
      email_discovery_status in (
        'not_started',
        'searching',
        'found',
        'not_found',
        'manual',
        'error'
      )
    );
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  alter table public.candidate_outreach
    add constraint candidate_outreach_sequence_status_check
    check (sequence_status in ('draft', 'active', 'paused', 'completed'));
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  alter table public.candidate_outreach
    add constraint candidate_outreach_active_step_check
    check (active_step between 0 and 4);
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  alter table public.candidate_outreach_message
    add constraint candidate_outreach_message_kind_check
    check (kind in ('sequence', 'manual'));
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  alter table public.candidate_outreach_message
    add constraint candidate_outreach_message_status_check
    check (status in ('draft', 'sent', 'skipped', 'canceled'));
exception
  when duplicate_object then null;
end
$$;
