insert into public.translation_entries (
  namespace,
  key,
  locale,
  value,
  status,
  updated_by
)
values
  ('career', 'career.common.career_flow_provider.06f4hcx', 'ko', '12시간 인사 스트림이 완료되기 전에 종료되었습니다.', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_flow_provider.06f4hcx', 'en', 'Ended before the 12-hour HR stream was completed.', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_flow_provider.0750gye', 'ko', '12시간 인사 생성에 실패했습니다.', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_flow_provider.0750gye', 'en', 'Failed to generate 12-hour HR.', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.0y27adb', 'ko', '진행중', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.0y27adb', 'en', 'In progress', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.1hsndwk', 'ko', '진행 종료', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.1hsndwk', 'en', 'Ended', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.1vrs10j', 'ko', '제외한 포지션', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.1vrs10j', 'en', 'Archived position', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.applied', 'ko', '지원함', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.applied', 'en', 'Applied', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.archived_tooltip', 'ko', '제외한 포지션', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.archived_tooltip', 'en', 'Archived position', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.hidden_tab', 'ko', '보관함', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.hidden_tab', 'en', 'Archive', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.interested_status', 'ko', '관심 있음', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.interested_status', 'en', 'Interested', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.saved_positions_tab', 'ko', '저장한 포지션', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.career_history_panel.saved_positions_tab', 'en', 'Saved positions', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.opportunity_type_meta.0ume46n', 'ko', '지원함', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.opportunity_type_meta.0ume46n', 'en', 'Applied', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.opportunity_type_meta.connected_stage_label', 'ko', '연결됨', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.opportunity_type_meta.connected_stage_label', 'en', 'Connected', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.opportunity_type_meta.external_negative_action', 'ko', '나와 안맞아요', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.opportunity_type_meta.external_negative_action', 'en', 'Not a fit', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.opportunity_type_meta.external_positive_action', 'ko', '관심 있어요', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.common.opportunity_type_meta.external_positive_action', 'en', 'Interested', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.career_mobile_jobs_view.1m3uw9j', 'ko', '관심 있는 포지션이 없습니다.', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.career_mobile_jobs_view.1m3uw9j', 'en', 'No interested positions yet.', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.career_mobile_jobs_view.mobile_connected_empty', 'ko', '진행중인 포지션이 없습니다.', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.career_mobile_jobs_view.mobile_connected_empty', 'en', 'You have no positions in progress.', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.history_oppotunity_info_modal.1ucb8t9', 'ko', '수락 후에도 마음이 바뀌면 하퍼에게 알려주시면 됩니다. 나와 안맞아요를 누른 경우에는 맞지 않는 이유를 다음 추천에서 비슷한 기회를 줄이는 데 반영합니다.', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.history_oppotunity_info_modal.1ucb8t9', 'en', 'If you change your mind after accepting, just let Harper know. If you select ''Not a fit,'' we''ll use the reason to reduce similar opportunities in future recommendations.', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.opportunity_detail_content.status_menu', 'ko', '{status} 상태 변경', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.opportunity_detail_content.status_menu', 'en', 'Change to {status} status', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.0obqas2', 'ko', '관심 있음', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.0obqas2', 'en', 'Interested', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.1jv953e', 'ko', '진행 종료', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.1jv953e', 'en', 'Ended', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.all', 'ko', '전체보기', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.all', 'en', 'View all', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.applied', 'ko', '지원함', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.applied', 'en', 'Applied', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.archived', 'ko', '제외한 포지션', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.archived', 'en', 'Archived position', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.connected', 'ko', '진행중', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.connected', 'en', 'In progress', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.hide_action', 'ko', '보관하기', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.history.saved_opportunity_status.hide_action', 'en', 'Archive', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.home.career_home_panel.11q0oj9', 'ko', '저장한 포지션', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.home.career_home_panel.11q0oj9', 'en', 'Saved positions', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'career.home.career_mobile_home_view.1vip5ub', 'ko', '저장한 포지션', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'career.home.career_mobile_home_view.1vip5ub', 'en', 'Saved positions', 'draft', 'migration:fix-career-english-status-labels'),
  ('career', 'ui.1787f9e', 'ko', '한국어', 'reviewed', 'migration:fix-career-english-status-labels'),
  ('career', 'ui.1787f9e', 'en', 'Korean', 'draft', 'migration:fix-career-english-status-labels')
on conflict (namespace, key, locale)
do update set
  value = excluded.value,
  status = excluded.status,
  updated_by = excluded.updated_by,
  updated_at = timezone('utc', now());

delete from public.translation_entries
where namespace = 'career'
  and key in (
    'career.history.saved_opportunity_status.0rjulen',
    'career.profile.language_selector.label'
  );
