create extension if not exists pgcrypto;

create table if not exists public.candidate_mark (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.company_users(user_id) on delete cascade,
  candid_id text not null references public.candid(id) on delete cascade,
  status text not null check (status in ('excluded', 'not_fit', 'hold', 'fit')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint candidate_mark_user_candidate_unique unique (user_id, candid_id)
);

create index if not exists candidate_mark_user_id_idx
  on public.candidate_mark (user_id);

create index if not exists candidate_mark_candid_id_idx
  on public.candidate_mark (candid_id);

alter table public.candidate_mark enable row level security;

drop policy if exists "candidate_mark_select_own" on public.candidate_mark;
create policy "candidate_mark_select_own"
  on public.candidate_mark
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "candidate_mark_insert_own" on public.candidate_mark;
create policy "candidate_mark_insert_own"
  on public.candidate_mark
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "candidate_mark_update_own" on public.candidate_mark;
create policy "candidate_mark_update_own"
  on public.candidate_mark
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "candidate_mark_delete_own" on public.candidate_mark;
create policy "candidate_mark_delete_own"
  on public.candidate_mark
  for delete
  to authenticated
  using (auth.uid() = user_id);

create table if not exists public.bookmark_folder_share (
  id uuid primary key default gen_random_uuid(),
  folder_id bigint not null references public.bookmark_folder(id) on delete cascade,
  created_by uuid not null references public.company_users(user_id) on delete cascade,
  token text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz null,
  revoked_at timestamptz null
);

create index if not exists bookmark_folder_share_folder_id_idx
  on public.bookmark_folder_share (folder_id, created_at desc);

create index if not exists bookmark_folder_share_created_by_idx
  on public.bookmark_folder_share (created_by, created_at desc);

alter table public.bookmark_folder_share enable row level security;

drop policy if exists "bookmark_folder_share_select_own" on public.bookmark_folder_share;
create policy "bookmark_folder_share_select_own"
  on public.bookmark_folder_share
  for select
  to authenticated
  using (auth.uid() = created_by);

drop policy if exists "bookmark_folder_share_insert_own" on public.bookmark_folder_share;
create policy "bookmark_folder_share_insert_own"
  on public.bookmark_folder_share
  for insert
  to authenticated
  with check (auth.uid() = created_by);

drop policy if exists "bookmark_folder_share_update_own" on public.bookmark_folder_share;
create policy "bookmark_folder_share_update_own"
  on public.bookmark_folder_share
  for update
  to authenticated
  using (auth.uid() = created_by)
  with check (auth.uid() = created_by);

drop policy if exists "bookmark_folder_share_delete_own" on public.bookmark_folder_share;
create policy "bookmark_folder_share_delete_own"
  on public.bookmark_folder_share
  for delete
  to authenticated
  using (auth.uid() = created_by);

create table if not exists public.bookmark_folder_share_note (
  id bigint generated by default as identity primary key,
  folder_id bigint not null references public.bookmark_folder(id) on delete cascade,
  candid_id text not null references public.candid(id) on delete cascade,
  viewer_key text not null,
  viewer_name text not null default '게스트',
  memo text not null check (char_length(trim(memo)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bookmark_folder_share_note_folder_candidate_idx
  on public.bookmark_folder_share_note (folder_id, candid_id, created_at desc);

create index if not exists bookmark_folder_share_note_viewer_idx
  on public.bookmark_folder_share_note (folder_id, viewer_key);

alter table public.bookmark_folder_share_note enable row level security;

-- Shared-folder notes are accessed only through server routes that use the
-- Supabase service role. No client-side RLS policy is added intentionally.
